name: Bug report 🐛
description: Create a bug report for TourGuideAI.
labels: ['status: needs triage']
body:
  - type: markdown
    attributes:
      value: |
        ### ⚠️ Before you continue
        * Check our [project roadmap](https://github.com/PaperStrange/TourGuideAI/projects/1) for planned features
        * If you need help, you can ask in the [discussions](https://github.com/PaperStrange/TourGuideAI/discussions) section
        * **Thoroughly search the [existing issues](https://github.com/PaperStrange/TourGuideAI/issues) before creating a new one**
        * Read our [contribution guidelines](https://github.com/PaperStrange/TourGuideAI/blob/main/CONTRIBUTING.md)

  - type: checkboxes
    attributes:
      label: ⚠️ Search for existing issues first ⚠️
      description: >
        Please [search the history](https://github.com/PaperStrange/TourGuideAI/issues)
        to see if an issue already exists for the same problem.
      options:
        - label: I have searched the existing issues, and there is no existing issue for my problem
          required: true

  - type: markdown
    attributes:
      value: |
        Please provide a clear and descriptive title for your issue ⬆️.
        
        For example:
        BAD - App keeps looping
        GOOD - After building locally, application goes into an infinite loop when loading the Map page
        
        Please help us by following these steps:
        - Search for existing issues and add a comment if you have the same or similar issue
        - Provide relevant details about your environment and steps to reproduce
        - Include screenshots or recordings if applicable

  - type: dropdown
    attributes:
      label: Which Operating System are you using?
      description: >
        Please select the operating system you were using when this problem occurred.
      options:
        - Windows
        - Linux
        - MacOS
        - Docker
        - Devcontainer / Codespace
        - Windows Subsystem for Linux (WSL)
        - Other
    validations:
      required: true
      nested_fields:
        - type: text
          attributes:
            label: Specify the system
            description: Please specify the system you are working on.

  - type: dropdown
    attributes:
      label: Which version of TourGuideAI are you using?
      description: |
        Please select which version of TourGuideAI you were using when this issue occurred.
        If you downloaded the code from the [releases page](https://github.com/PaperStrange/TourGuideAI/releases/) make sure you were using the latest code.
        **If you weren't please try with the [latest code](https://github.com/PaperStrange/TourGuideAI/releases/)**.
        If installed with git you can run `git branch` to see which version you are running.
      options:
        - Latest Release (v0.5.1)
        - Stable Branch
        - Main Branch
        - Development Branch
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Which API service are you using?
      description: >
        Please select which API service you were using when this issue occurred.
      options:
        - Google Maps API
        - OpenAI API
        - Weather API
        - Multiple APIs
        - None
        - Other (detail in issue)
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Which area covers your issue best?
      description: >
        Select the area related to the issue you are reporting.
      options:
        - Installation and setup
        - User Interface
        - Maps functionality
        - Route planning
        - API integration
        - Performance
        - Offline functionality
        - Mobile compatibility
        - Authentication
        - Documentation
        - Other
    validations:
      required: true
      autolabels: true
      nested_fields:
        - type: text
          attributes:
            label: Specify the area
            description: Please specify the area you think is best related to the issue.

  - type: input
    attributes:
      label: What commit or version are you using?
      description: It is helpful for us to reproduce to know what version of the software you were using when this happened. Please run `git log -n 1 --pretty=format:"%H"` to output the full commit hash.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe your issue.
      description: Describe the problem you are experiencing. Try to be clear and concise. Include steps to reproduce if possible.
    validations:
      required: true

  #Following are optional file content uploads
  - type: markdown
    attributes:
      value: |
        ⚠️The following is OPTIONAL, please keep in mind that log files may contain personal information.⚠️
        
        "Log files are located in the 'logs' folder inside the main TourGuideAI folder."

  - type: textarea
    attributes:
      label: Upload Application Log Content
      description: |
        Upload the application log content to help us understand the issue better. 
        To do this, go to the 'logs' folder in your main TourGuideAI folder, open application.log and copy/paste the contents to this field.
        ⚠️ Please remove any personal or sensitive information before sharing. ⚠️
    validations:
      required: false

  - type: textarea
    attributes:
      label: Upload Error Log Content
      description: |
        Upload the error log content to help us understand the issue better.
        To do this, go to the 'logs' folder in your main TourGuideAI folder, open error.log and copy/paste the contents to this field.
        ⚠️ Please remove any personal or sensitive information before sharing. ⚠️
    validations:
      required: false
