// Interface copy for the shared-perspective experiment, independent of legacy UI.
// Place facts and contributed stories belong to content, not this catalog.
export const COPY = {
  en: {
    brand: 'TourGuideAI',
    title: 'Borrow someone’s eyes',
    subtitle: 'A little Kyoto, from another point of view.',
    intro: 'Follow a view. Notice a detail. Leave a thought of your own.',
    modeLabel: 'How would you like to explore?',
    modeWalk: 'Walk & look',
    modeStory: 'Map & story',
    startWalk: 'Walk into the scene',
    startStory: 'Open the map & story',
    switchMode: 'Try the other view',
    languageLabel: 'Language',
    languageEn: 'English',
    languageZh: '中文',
    controlsTitle: 'Find your way',
    controlsMove: 'Walk',
    controlsLook: 'Drag to look around',
    controlsZoom: 'Scroll to zoom',
    keyMove: 'WASD / arrow keys',
    lookHere: 'Look here',
    resetView: 'Reset view',
    arrivalTitle: 'Arrive with curiosity',
    arrivalBody: 'Take a look around. There’s a small detail waiting to be noticed.',
    discoveryTitle: 'A different way to notice',
    discoveryBody: 'Follow this view, then see what caught the author’s attention.',
    endingTitle: 'What caught your eye?',
    endingBody: 'Keep a view or a thought, or simply carry on exploring.',
    continueWalk: 'Keep exploring',
    finishWalk: 'Finish this little walk',
    sampleAuthor: 'Studio sample · not a traveler account',
    sampleContext: 'The team wrote this example to invite a closer look.',
    noteLabel: 'Your observation',
    notePlaceholder: 'What did you notice?',
    noteHelp: 'One sentence is enough. You can keep it to yourself.',
    saveNote: 'Save this moment',
    editNote: 'Reopen & edit',
    deleteNote: 'Delete my note',
    noteSaved: 'Your note is saved on this device.',
    noteDeleted: 'Your note has been deleted.',
    noteEmpty: 'No personal note yet.',
    noteLimit: '{count}/{max} characters',
    notePrivate: 'Your note stays private until you choose to share it.',
    frameView: 'Keep this view',
    viewFramed: 'This view is selected for your moment.',
    shareOpen: 'Preview & share',
    shareTitle: 'A moment to share',
    shareIntro: 'Review the view and words you’ll send.',
    sharePreview: 'What the recipient will see',
    shareCopy: 'Copy link',
    shareNative: 'Share moment',
    shareLinkCopied: 'Link copied',
    shareUnavailable: 'The link couldn’t be shared or copied. Please try again.',
    shareCancelled: 'Sharing cancelled. Your moment is still here.',
    shareHandedOff: 'Passed to your device’s share service',
    shareClose: 'Keep editing',
    shareEmpty: 'There’s no personal moment to share yet.',
    shareTooLong: 'This link is too long. Shorten your note and try again.',
    recipientTitle: 'A view someone wanted to share',
    recipientReadOnly: 'A shared moment from a virtual walk. Your own walk stays unchanged.',
    recipientStartOwn: 'Find a view of my own',
    backToWalk: 'Back to my walk',
    storageUnavailable: 'Changes can’t be saved on this device. Keep a copy of your note before leaving.',
    reset: 'Begin again',
    resetConfirm: 'Start again and clear this walk’s saved view, note and reflection on this device?',
    resetCancel: 'Keep my walk',
    resetConfirmAction: 'Start again',
    reflectionTitle: 'A quick reflection · optional',
    reflectionQuestion: 'How enjoyable was this experience?',
    reflectionLow: '1 · Not enjoyable',
    reflectionHigh: '5 · Very enjoyable',
    reflectionSkip: 'Skip reflection',
    reflectionSaved: 'Thank you for the reflection.',
    reflectionReasonLabel: 'What would make you continue—or stop? (optional)',
    reflectionReasonPlaceholder: 'A detail you liked, or something that got in the way…',
    reflectionContinue: 'I’d keep exploring',
    reflectionStop: 'I’d stop here',
    loading: 'Opening this little view…',
    loadError: 'This view couldn’t open. Please try again.',
    retry: 'Try again',
    close: 'Close',
    back: 'Back',
    begin: 'Begin this little journey',
    savedMoments: 'My moments',
    savedView: 'Saved view',
    walkHere: 'Walk to this viewpoint',
    onTheWay: 'On the way…',
    arrived: 'You’re here. Take a look.',
    reveal: 'Read the studio’s thought',
    sourceLabel: 'About this place',
    illustrated: 'Illustrated view · not a photograph',
    includeNote: 'Include my saved note',
    referencePreview: 'Reference illustration. The link opens your saved 3D framing.',
    saved3DView: 'Saved 3D view',
    storyFallback: 'Showing a reference illustration; your saved 3D framing is unchanged.',
    useStory: 'Continue with map & story',
    feedbackLocal: 'Feedback stays on this device. Download it if you want to share it.',
    exportFeedback: 'Download my feedback',
    chooseScore: 'Choose a score',
    invalidShare: 'This shared moment could not be read.',
    copyManually: 'Select and copy this link',
    momentSaved: 'Your view and note are saved on this device.',
    deleteMoment: 'Remove this moment',
    remaining: 'Three observations, one small loop',
    existingWalk: 'Open the original walk',
    stop: 'Finish for now',
    resume: 'Resume this view',
    scope: 'A short virtual walk around Shijō–Karasuma, Kyoto.',
    sharedNoteLabel: 'Shared observation',
    controlsTap: 'Tap the street to walk',
  },
  zh: {
    brand: 'TourGuideAI',
    title: '借一双眼睛',
    subtitle: '换个视角，看一小段京都。',
    intro: '跟随一个视角，留意一个细节，留下你的发现。',
    modeLabel: '你想怎样探索？',
    modeWalk: '边走边看',
    modeStory: '地图与故事',
    startWalk: '走进街景',
    startStory: '打开地图与故事',
    switchMode: '换一种方式看看',
    languageLabel: '语言',
    languageEn: 'English',
    languageZh: '中文',
    controlsTitle: '自在走走',
    controlsMove: '行走',
    controlsLook: '拖动环顾',
    controlsZoom: '滚动缩放',
    keyMove: 'WASD / 方向键',
    lookHere: '看向这里',
    resetView: '重置视角',
    arrivalTitle: '带着好奇心抵达',
    arrivalBody: '先环顾一下，有个小细节等你发现。',
    discoveryTitle: '换个角度，留意这里',
    discoveryBody: '跟随这个视角，看看是什么吸引了作者的注意。',
    endingTitle: '什么吸引了你的目光？',
    endingBody: '留下一幅视角、一点感想，或继续自在探索。',
    continueWalk: '继续探索',
    finishWalk: '结束这段漫步',
    sampleAuthor: '创作示例 · 非旅行者投稿',
    sampleContext: '这段示例由团队创作，邀请你走近看看。',
    noteLabel: '你的发现',
    notePlaceholder: '你留意到了什么？',
    noteHelp: '一句话就好，也可以只留给自己。',
    saveNote: '保存这一刻',
    editNote: '重新打开与编辑',
    deleteNote: '删除我的笔记',
    noteSaved: '笔记已保存在此设备上。',
    noteDeleted: '笔记已删除。',
    noteEmpty: '还没有个人笔记。',
    noteLimit: '{count}/{max} 字符',
    notePrivate: '笔记只留给你，直到你选择分享。',
    frameView: '留下这个视角',
    viewFramed: '已选用这个视角，记录这一刻。',
    shareOpen: '预览与分享',
    shareTitle: '分享这一刻',
    shareIntro: '先看看即将发送的画面和文字。',
    sharePreview: '对方将看到的内容',
    shareCopy: '复制链接',
    shareNative: '分享这一刻',
    shareLinkCopied: '链接已复制',
    shareUnavailable: '暂时无法分享或复制链接，请再试一次。',
    shareCancelled: '已取消分享，这一刻仍然保留。',
    shareHandedOff: '已交给设备的分享功能',
    shareClose: '继续编辑',
    shareEmpty: '还没有可分享的个人记录。',
    shareTooLong: '链接过长，请缩短笔记后再试。',
    recipientTitle: '有人想与你分享这个视角',
    recipientReadOnly: '这是一段虚拟漫步中的分享，不会改变你自己的漫步。',
    recipientStartOwn: '寻找我的视角',
    backToWalk: '回到我的漫步',
    storageUnavailable: '此设备暂时无法保存更改，请在离开前自行保留笔记。',
    reset: '重新开始',
    resetConfirm: '重新开始，并清除此设备上这段漫步保存的视角、笔记和反馈？',
    resetCancel: '保留我的漫步',
    resetConfirmAction: '重新开始',
    reflectionTitle: '一点感受 · 可选',
    reflectionQuestion: '你有多享受这段体验？',
    reflectionLow: '1 · 没有乐趣',
    reflectionHigh: '5 · 很有乐趣',
    reflectionSkip: '跳过反馈',
    reflectionSaved: '谢谢你留下感受。',
    reflectionReasonLabel: '什么会让你想继续，或停下来？（可选）',
    reflectionReasonPlaceholder: '一个喜欢的细节，或一处让你不太顺畅的地方……',
    reflectionContinue: '我想继续看看',
    reflectionStop: '我想先停在这里',
    loading: '正在展开这幅小小的街景…',
    loadError: '暂时无法打开这个视角，请再试一次。',
    retry: '重试',
    close: '关闭',
    back: '返回',
    begin: '开始这段小小的旅程',
    savedMoments: '我的记录',
    savedView: '已保存的视角',
    walkHere: '走到这个观察点',
    onTheWay: '正在前往…',
    arrived: '到了，看看这里。',
    reveal: '读读团队的感想',
    sourceLabel: '关于这个地方',
    illustrated: '插画视图 · 非照片',
    includeNote: '附上我已保存的笔记',
    referencePreview: '这是参考插画。链接会打开你保存的三维视角。',
    saved3DView: '已保存的三维视角',
    storyFallback: '目前显示参考插画，你保存的三维视角仍然保留。',
    useStory: '继续浏览地图与故事',
    feedbackLocal: '反馈保留在此设备上。如需分享，可以下载。',
    exportFeedback: '下载我的反馈',
    chooseScore: '选择评分',
    invalidShare: '暂时无法读取这个分享。',
    copyManually: '选中并复制这条链接',
    momentSaved: '视角与笔记已保存在此设备上。',
    deleteMoment: '删除这条记录',
    remaining: '三处发现，一段小小的漫步',
    existingWalk: '打开原版漫步',
    stop: '先到这里',
    resume: '回到这个视角',
    scope: '京都四条乌丸附近的一段简短虚拟漫步。',
    sharedNoteLabel: '分享者的发现',
    controlsTap: '轻点街道行走',
  },
};

/** Plain text only; callers choose the appropriate rendering and escaping. */
export function text(locale, key, vars = {}) {
  const catalog = String(locale).toLowerCase().startsWith('zh') ? COPY.zh : COPY.en;
  const template = Object.hasOwn(catalog, key) ? catalog[key] : COPY.en[key];
  if (typeof template !== 'string') return String(key);
  return template.replace(/\{(\w+)\}/g, (match, name) =>
    Object.hasOwn(vars, name) ? String(vars[name]) : match,
  );
}
