#!/usr/bin/env node
/**
 * bake-viewer.mjs — build `iteration/viewer/index.html`: the walkable shell.
 *
 * WHAT IT EMITS, AND WHY IT IS ONE FILE
 * -------------------------------------
 * A single self-contained HTML page with no network access of any kind. That is
 * not tidiness, it is the requirement: Chrome and Firefox refuse to load a module
 * script from `file://` (it is treated as a CORS request), and even a classic
 * `<script src="…">` is refused. A viewer that needs `python -m http.server`
 * before it opens is a viewer someone has to explain, and Gate 1's criterion is
 * that ONE REAL PERSON walks it. So the four layers, the manifest, the street
 * profile, the doors and the walker are all inlined.
 *
 * THE WALKER ON THE PAGE IS NOT A COPY
 * ------------------------------------
 * The simulation functions are serialised out of `check-viewer.mjs` with
 * `.toString()` and re-evaluated in the page. The browser therefore runs the same
 * function BODIES that the headless assertions check. A hand-written second copy
 * would be a second source of truth, and this project has already paid for one of
 * those (D-12: the valueKind enum mirrored into doors.json went stale).
 *
 * The layers ship as base64 because the payload has to survive living inside a
 * `<script>` tag. The obvious optimisation — one JSON object with a small numeric
 * alphabet — needs a character like `<` or a quote in that alphabet and then the
 * payload can terminate the tag early. Base64's alphabet is [A-Za-z0-9+/=], which
 * cannot appear in `</script>`, and the trailing `=` padding is trimmed here and
 * restored on decode.
 *
 * USAGE
 *   node iteration/tools/bake-viewer.mjs            bake
 *   node iteration/tools/bake-viewer.mjs --bake-if-absent   bake scene.bin first
 *
 * Exit codes: 0 = baked, 1 = a problem, 2 = environment (no scene.bin).
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { SCENE_VERSION, SCENE_MAGIC } from './emit-scene.mjs';
import { join, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';

import {
  walkStreet, doorReport, reachableSet, streetRowAt, frameHashInput, isBlocked, idx,
  serialiseSimulation, sha256Hex,
} from './check-viewer.mjs';
import { openDoor } from './viewer-interaction.mjs';

const REPO = resolve(import.meta.dirname, '..', '..');
const SCENE = join(REPO, 'build', 'scene.bin');
const GUIDE = join(REPO, 'build', 'guide.json');
/**
 * `--doors <path>` and `--opener <path>` are FIRE-DRILL overrides, the same shape as
 * `validate-doors.mjs --doors`: bake a variant against an alternate fact layer so the
 * assertions can be shown to follow their inputs. `--out <dir>` keeps the drill away
 * from the shipped page, because a demonstration that can overwrite the artefact is
 * not a drill.
 */
const DOORS = (() => {
  const i = process.argv.indexOf('--doors');
  return i >= 0 && process.argv[i + 1]
    ? resolve(process.argv[i + 1])
    : join(REPO, 'city-packs', 'kyoto-shijo', 'doors.json');
})();
/**
 * The DECLARATION of which doors are openable and what kind of surface each has.
 * Generated by `build-opener-fact.mjs`; this baker consumes it and never decides it.
 */
const OPENER = (() => {
  const i = process.argv.indexOf('--opener');
  return i >= 0 && process.argv[i + 1]
    ? resolve(process.argv[i + 1])
    : join(REPO, 'iteration', 'viewer', 'opener-contract.json');
})();
/**
 * `--out <dir>` exists so a FIRE DRILL can bake a variant somewhere else and run the
 * checks against it. The demonstration the task card asks for — point the checks at a
 * 9-door input and show the assertions FOLLOW rather than redden — must not be able to
 * touch the shipped page, or the drill becomes the incident.
 */
const OUT_DIR = (() => {
  const i = process.argv.indexOf('--out');
  return i >= 0 && process.argv[i + 1] ? resolve(process.argv[i + 1]) : join(REPO, 'iteration', 'viewer');
})();
const OUT = join(OUT_DIR, 'index.html');

const { worldGrid, GRID, ORIGIN, quantizeToSubTile, locateSubTile } = await import(
  new URL('../../docs/handOff/dsh-bundle-tourguide-2.5d/tools/world-grid.mjs', import.meta.url).href
);

function die(code, msg) {
  process.stderr.write(`${msg}\n`);
  process.exit(code);
}

/* ------------------------------------------------------------------ *
 * Read the scene. FAIL LOUDLY: build/ is gitignored, so a clean clone has
 * no scene.bin and this must say exactly what to run rather than emit a
 * page that silently renders nothing.
 * ------------------------------------------------------------------ */
if (!existsSync(SCENE)) {
  if (!process.argv.includes('--bake-if-absent')) {
    die(2,
      `no scene.bin at ${SCENE}\n` +
      `  build/ is gitignored, so a clean clone has none.\n` +
      `  run: node iteration/tools/emit-scene.mjs    (or pass --bake-if-absent)`);
  }
  const r = spawnSync(process.execPath, [join(REPO, 'iteration', 'tools', 'emit-scene.mjs')], { cwd: REPO, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
  if (r.status !== 0) die(2, `could not bake the scene (exit ${r.status}): ${((r.stdout || '') + (r.stderr || '')).slice(-500)}`);
}
if (!existsSync(GUIDE)) {
  die(2,
    `no guide.json at ${GUIDE}\n` +
    `  the walk must be reconciled against the game's EXPORT, and the export is guide.json.\n` +
    `  run: node iteration/tools/emit-guide.mjs`);
}
if (!existsSync(OPENER)) {
  die(2,
    `no opener-contract.json at ${OPENER}\n` +
    `  which doors are openable, and of what kind, is a FACT-LAYER DECLARATION; this baker\n` +
    `  consumes it and does not decide it. It is generated, not hand-written:\n` +
    `  run: node iteration/tools/build-opener-fact.mjs`);
}

const buf = readFileSync(SCENE);
const W = buf.readUInt32LE(12);
const H = buf.readUInt32LE(16);
const manifestLen = buf.readUInt32LE(104);
const manifest = JSON.parse(buf.toString('utf8', 108, 108 + manifestLen));
const o = 108 + manifestLen;
const n = W * H;
const ground = buf.subarray(o, o + n);
const collision = buf.subarray(o + n, o + 2 * n);
const heights = buf.subarray(o + 2 * n, o + 3 * n);
const occlusionHalf = buf.subarray(o + 3 * n, o + 3 * n + W);
const openings = buf.subarray(o + 3 * n + W, o + 4 * n + W);

// Re-assert the container here rather than trusting it: this baker is a fourth
// reader, and a fourth reader that assumes is a fourth chance to be wrong.
if (buf.toString('ascii', 0, 8) !== SCENE_MAGIC || buf.readUInt32LE(8) !== SCENE_VERSION ||
    W !== worldGrid.wTiles || H !== worldGrid.hTiles ||
    108 + manifestLen + (n * 4 + W) !== buf.length) {
  die(1, `scene.bin does not match the frozen contract header (${W}x${H}, manifest ${manifestLen}, ${buf.length} B)`);
}

const SCENE_SHA = sha256Hex(buf);
const profile = manifest.street ? manifest.street.profile : null;
if (!profile) die(1, 'scene manifest carries no street.profile — the walker cannot know where the street is');

const doorsFile = JSON.parse(readFileSync(DOORS, 'utf8'));
const doors = doorsFile.doors;
const guide = JSON.parse(readFileSync(GUIDE, 'utf8'));
const opener = JSON.parse(readFileSync(OPENER, 'utf8'));

/* ------------------------------------------------------------------ *
 * Run the walk and the door analysis HERE, so the page opens showing a
 * correct, already-verified state instead of an empty canvas.
 * ------------------------------------------------------------------ */
const reached = reachableSet(collision, W, H, 0);
const walk = walkStreet(profile, collision, W, H, GRID.halfCrossTiles, {});
const doorsReport = doorReport(doors, profile, collision, W, H, GRID.halfCrossTiles, reached);

const placeById = new Map();
for (const s of [...guide.stops, ...guide.nearby]) placeById.set(s.placeId, s);
// doors.json names its building by OSM way; the bridge to the export is the fact
// layer's entrances.doorIds (the same bridge check-viewer.mjs V5 walks).
const placesFile = JSON.parse(readFileSync(join(REPO, 'city-packs', 'kyoto-shijo', 'places.json'), 'utf8'));
const doorToPlace = new Map();
for (const p of placesFile) {
  if (!p.entrances || !Array.isArray(p.entrances.doorIds)) continue;
  for (const id of p.entrances.doorIds) doorToPlace.set(id, p.id);
}

const doorMarkers = doorsReport.map((d) => {
  const placeId = doorToPlace.get(d.doorId) || null;
  const place = placeId ? placeById.get(placeId) : null;
  /**
   * The interaction is RESOLVED HERE, by the same `openDoor` body the page and the
   * assertions both use — so what the page shows is what was checked, and the page
   * never re-derives it. `surface` comes from the declaration, never from `depthBehind`.
   */
  const declared = (opener.openable || []).find((o) => o.doorId === d.doorId) || null;
  const interaction = openDoor(d.doorId, opener, { doors: doorsReport });
  return {
    ...d,
    placeId,
    placeNameJa: place ? place.nameJa : null,
    inGuide: Boolean(place),
    openable: declared ? declared.openable : false,
    surface: declared ? declared.surface : null,
    interaction,
  };
});

/* ------------------------------------------------------------------ *
 * Layers -> base64 with trailing '=' trimmed ('=' cannot be trusted to
 * survive some editors; the length is in the payload, so it is restored).
 * ------------------------------------------------------------------ */
const b64 = (view) => Buffer.from(view).toString('base64').replace(/=+$/, '');

const payload = {
  schema: 'tourguide.viewer-scene/v1',
  scene: {
    path: 'build/scene.bin',
    sha256: SCENE_SHA,
    bytes: buf.length,
    grid: { wTiles: W, hTiles: H },
    chunksAlongX: buf.readUInt32LE(20),
    origin: { lonUdeg: ORIGIN.lonUdeg, latUdeg: ORIGIN.latUdeg },
    contractHash: buf.toString('ascii', 40, 104),
  },
  halfCrossTiles: GRID.halfCrossTiles,
  street: { driftSpanM: manifest.street.driftSpanM, profile },
  layers: {
    encoding: 'base64, trailing = trimmed',
    byteLengths: { ground: n, collision: n, heights: n, occlusionHalf: W, openings: n },
    ground: b64(ground),
    collision: b64(collision),
    heights: b64(heights),
    occlusionHalf: b64(occlusionHalf),
    openings: b64(openings),
  },
  /**
   * The DECLARATION travels into the page, and so does the interaction source. The page
   * consumes them; it does not decide which doors are openable, and it does not carry a
   * second copy of the placeholder string.
   */
  openerContract: {
    schema: opener.schema,
    generatedBy: opener.generatedBy,
    surfaceKinds: opener.surfaceKinds,
    modelRule: opener.modelRule,
    counts: opener.counts,
    openable: opener.openable,
  },
  doors: doorMarkers,
  walk: {
    reachedX: walk.reachedX,
    steps: walk.steps,
    corrections: walk.corrections,
    stoppedAt: walk.stoppedAt,
    startRow: walk.path.length ? walk.path[0].row : null,
    endRow: walk.path.length ? walk.path[walk.path.length - 1].row : null,
    path: walk.path,
  },
  guide: {
    path: 'build/guide.json',
    schema: guide.schema,
    stopCount: guide.stops.length,
    nearbyCount: guide.nearby.length,
    placeCount: guide.stops.length + guide.nearby.length,
    // only what the overlay needs, so the page cannot become a second export
    stops: guide.stops.map((s) => ({ seq: s.seq, placeId: s.placeId, nameJa: s.nameJa, nameZh: s.nameZh, alongStreetM: s.alongStreetM })),
  },
  anchors: ANCHORS,
  /**
   * THE TWO VARIANTS. V-A is bare (no instructional text at all), V-B adds a keymap
   * that says ONLY which keys move — no goal, no colour legend. They exist to separate
   * the third cause of "nothing happens": the keys may simply not be discoverable. A
   * keymap that also explained the goal would confound that, so it does not.
   */
  variants: {
    'V-A': { id: 'V-A', label: 'bare', keymap: false, instructionalText: [] },
    'V-B': { id: 'V-B', label: 'keymap', keymap: true, instructionalText: ['keymap: arrows or WASD move · E opens the door you stand at'] },
  },
  defaultVariant: 'V-A',
};

/* ------------------------------------------------------------------ *
 * THE ANCHORS — the pure-function target set for `next` (play-systems.md §1.7)
 *
 * `anchors := guide.json's inSceneWindow records ∪ doors.json's doorways`, each with a
 * real name, a cell, per-field provenance and a source. Nothing here is invented: the
 * name and its valueKind come from guide.json's cells, the source URL from the same
 * cell, and the CELL is computed by the contract's own quantiser — quantizeToSubTile +
 * locateSubTile — NOT by rounding.
 *
 * That last point is a correction worth recording: `cellX = round(alongStreetM)` looked
 * obvious and DISAGREED with guide.json on 3 of its 4 recorded tiles (e.g. 四条河原町
 * バス停D: round gives row 16, the contract's quantiser gives row 15). The quantiser
 * reproduced all four exactly. A second, plausible-looking conversion was wrong.
 * ------------------------------------------------------------------ */
function cellOf(alongStreetM, acrossStreetM) {
  const sub = quantizeToSubTile(alongStreetM, acrossStreetM);
  const at = locateSubTile(sub.subX, sub.subY);
  return { cellX: at.tileX, cellY: at.row, subX: sub.subX, subY: sub.subY, inWindow: at.inWindow };
}

const placeByAnchorId = new Map();
for (const p of placesFile) placeByAnchorId.set(p.id, p);

function cellsFromGuideRow(r) {
  const all = [...(r.verified || []), ...(r.otherKinds || [])];
  const nameCell = all.find((c) => c.field === r.nameFieldUsed) || all.find((c) => c.field === 'nameJa') || null;
  return {
    nameFieldKind: nameCell ? nameCell.valueKind : null,
    sourceUrl: nameCell ? nameCell.sourceUrl : null,
    verifiedFields: (r.verified || []).map((c) => ({ field: c.field, value: c.value, valueKind: c.valueKind, sourceUrl: c.sourceUrl })),
  };
}

const ANCHORS = [];
for (const r of [...guide.stops, ...guide.nearby]) {
  if (!r.inSceneWindow) continue;
  const p = placeByAnchorId.get(r.placeId) || null;
  const c = cellOf(r.alongStreetM, r.acrossStreetM);
  const cells = cellsFromGuideRow(r);
  ANCHORS.push({
    kind: 'place',
    id: r.placeId,
    nameJa: r.nameJa,
    nameZh: r.nameZh || null,
    alongStreetM: r.alongStreetM,
    acrossStreetM: r.acrossStreetM,
    cellX: c.cellX,
    cellY: c.cellY,
    nameFieldKind: cells.nameFieldKind,
    modelled: true,   // a real place with a source: always eligible to be named
    verifiedFields: cells.verifiedFields,
    sourceUrl: cells.sourceUrl || (p ? p.source_url : null),
    verifiedAt: p ? p.verified_at : null,
  });
}
for (const d of doorMarkers) {
  ANCHORS.push({
    kind: 'doorway',
    id: d.doorId,
    nameJa: d.placeNameJa || d.doorId,
    nameZh: null,
    alongStreetM: d.cellX,
    acrossStreetM: d.cellY - GRID.halfCrossTiles,
    cellX: d.cellX,
    cellY: d.cellY,
    nameFieldKind: 'authored',
    verifiedFields: [],
    sourceUrl: null,
    verifiedAt: null,
    surface: d.surface,
    openable: d.openable,
    /**
     * The spec's `modelled` flag, and it is the one that decides whether this door can be
     * NAMED as the next target (§1.7's `eligible`). `modelled: false` means the shopfront
     * is real but this engine has no interior geometry behind it — a placeholder door.
     *
     * It is still drawn, still enterable, still counted in 门洞 n/10. Only the pointing is
     * gated. Without this clause the target sequence walks the player through three
     * 「内容开发中」 doors in a row, because they sit in a 7 m chain on row 0.
     */
    modelled: d.surface !== 'unmodelled-interior',
  });
}
// deterministic order, so `next`'s tie-break is reproducible rather than incidental
ANCHORS.sort((a, b) => (a.alongStreetM - b.alongStreetM) || (a.id < b.id ? -1 : 1));

/* ------------------------------------------------------------------ *
 * The page. Plain HTML + one classic <script>. No imports, no fetch.
 * ------------------------------------------------------------------ */
const simSource = serialiseSimulation();

const html = `<!DOCTYPE html>
<html lang="zh-Hans">
<head>
<meta charset="utf-8">
<title>四条通 — walkable shell (Gate 1)</title>
<style>
  :root { --ink:#16161D; --paper:#F6F2EA; --ok:#1F6B3A; --warn:#8A5A00; --unknown:#6B6B6B; }
  * { box-sizing: border-box; }
  body { margin:0; background:var(--paper); color:var(--ink);
         font:13px/1.45 ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; }
  header { padding:9px 14px; border-bottom:1px solid #d8d2c4; display:flex; gap:16px; flex-wrap:wrap; align-items:baseline; }
  header h1 { font-size:15px; margin:0; font-weight:700; }
  header .k { color:var(--unknown); }
  #hud { background:rgba(246,242,234,.95); padding:6px 14px; border-bottom:1px solid #d8d2c4; }
  .pill { display:inline-block; padding:1px 6px; border:1px solid #d8d2c4; border-radius:2px; margin-right:6px; }
  .ok { color:var(--ok); } .warn { color:var(--warn); } .dim { color:var(--unknown); }
  #scroll { padding:12px 14px; }
  canvas { display:block; border:1px solid #d8d2c4; background:#fff; max-width:100%; }
  .panel { margin-top:10px; max-width:640px; }
  .ph-title { font-weight:700; margin-bottom:4px; }
  /* The placeholder must be unmissable, and visually unlike a measured room. */
  .ph-flag { display:inline-block; background:#8A5A00; color:#fff; padding:3px 10px;
             font-weight:700; letter-spacing:.04em; margin:2px 0 4px; }
  .ok-flag { display:inline-block; background:#1F6B3A; color:#fff; padding:3px 10px;
             font-weight:700; letter-spacing:.04em; margin:2px 0 4px; }
  .ph-note { color:var(--unknown); font-size:12px; margin:2px 0; }
  #room { margin-top:6px; border:1px solid #d8d2c4; }
  table { border-collapse:collapse; margin-top:10px; font-size:12px; }
  td, th { border:1px solid #d8d2c4; padding:2px 7px; text-align:left; }
  th { background:#efe9dc; }
</style>
</head>
<body>
<header>
  <h1>四条通 — walkable shell</h1>
  <span><span class="k">scene</span> ${SCENE_SHA.slice(0, 16)}…</span>
  <span><span class="k">contract</span> ${payload.scene.contractHash.slice(0, 16)}…</span>
  <span><span class="k">grid</span> ${W}×${H}</span>
</header>
<div id="hud">
  <span class="pill">↑ ↓ ← → / WASD walk</span>
  <span class="pill">E open a door</span>
  <span class="pill">[ ] zoom</span>
  <span class="pill dim">green = walkable · dark = collision · grey = building footprint · red = door</span>
</div>
<div id="scroll">
  <canvas id="c"></canvas>
  <div id="pos"></div>
  <div id="panel" class="panel"></div>
  <div id="legend"></div>
</div>

<script id="__TG_SCENE__" type="application/json">${JSON.stringify(payload)}</script>
<script>
(function () {
  'use strict';
  var PAYLOAD = JSON.parse(document.getElementById('__TG_SCENE__').textContent);

  /* --- decode the frozen layers ------------------------------------- */
  function b64view(s, expectedLen) {
    var pad = (4 - (s.length % 4)) % 4;
    var bin = atob(s + Array(pad + 1).join('='));
    var out = new Uint8Array(bin.length);
    for (var i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
    if (expectedLen !== undefined && out.length !== expectedLen) {
      throw new Error('layer length ' + out.length + ' but the payload declares ' + expectedLen);
    }
    return out;
  }
  var W = PAYLOAD.scene.grid.wTiles, H = PAYLOAD.scene.grid.hTiles;
  var L = PAYLOAD.layers.byteLengths;
  var ground = b64view(PAYLOAD.layers.ground, L.ground);
  var collision = b64view(PAYLOAD.layers.collision, L.collision);
  var heights = b64view(PAYLOAD.layers.heights, L.heights);
  var occlusionHalf = b64view(PAYLOAD.layers.occlusionHalf, L.occlusionHalf);

  /* --- THE simulation, serialised out of check-viewer.mjs -------------
     Same function bodies the headless assertions ran against. Not a copy. */
  var SIM = ${simSource};

  /* --- the camera ----------------------------------------------------
     SCALE IS FROM THE SPEC, NOT FROM TASTE. appendix-visual-and-ui-spec.md:
       §1.1 L17  tile is 32x32 px, 1 tile = 1 m, one block = 40x40 tiles = 1280x1280 px
       §1.2 L25  zoom is an INTEGER, 1/2/3 only (non-integers make the pixels shimmer)
       §1.2 L27  logical canvas 1280x720
       §1.2 L29  zoom table: zoom 1 sees 1280 px of world = 40 tiles; zoom 2 sees 640 px
                 = 20 tiles; zoom 3 sees 426.7 px = 13.3 tiles
       §1.2 L35  every interior fits on one screen at zoom 2; interiors never scroll
       L131      "zoom 2 -> 640x360 world pixels, x2 -> 1280x720"

     => screenScale = zoom. A tile is 32 world px, so on screen it is 32 x zoom px: 32 at
        zoom 1, 64 at zoom 2, 96 at zoom 3. zoom 1 is the pano/debug view, zoom 2 is the
        default the rest of the spec assumes, zoom 3 is signboard study. L22 confirms it
        independently: a 12 px world glyph is 24 px on screen at zoom 2.

     THE FIRST VERSION OF THIS CORRECTION HAD THE RATIO INVERTED (32/zoom), which made
     zoom 2 show 80 tiles instead of 20 — it zoomed OUT where the spec zooms IN. The
     arithmetic looked plausible and my own new assertion passed, because that assertion
     had been written from the same wrong reading. What settled it was L131's "x2", not
     any table cell. A wrong reading and an assertion built on it agree with each other.

     NO BACKTICKS IN THIS BLOCK: the page's JavaScript is emitted inside a template
     literal, so a backtick here terminates it early — the same failure class as a literal
     closing script tag. */
  var TILE_PX = 32;                      // spec §1.1: one tile is 32x32 world px
  var ZOOM_LEVELS = [1, 2, 3];           // spec §1.2: integers only, non-integers shimmer
  var DEFAULT_ZOOM_INDEX = 1;            // -> zoom 2, the level the spec's rules assume
  var zoomIdx = DEFAULT_ZOOM_INDEX;

  function zoomLevel() { return ZOOM_LEVELS[zoomIdx]; }
  /** Screen pixels per WORLD pixel. Spec L131: zoom 2 maps 640 world px onto 1280. */
  function screenScale() { return zoomLevel(); }
  /** Screen pixels per tile: 32 world px, each screenScale() screen px across. */
  function scale() { return TILE_PX * screenScale(); }
  /**
   * The spec's logical width is 1280 px and its zoom table is that width over the 32
   * world px in a tile, so 1280 / 32 / zoom reproduces the table exactly: 40 / 20 / 13.3.
   * The logical HEIGHT assumes 16:9, while this corridor is 40 rows — so the HEIGHT comes
   * from the world (all 40 rows always visible, the walk is never vertically blind) and
   * the WIDTH from the spec. The adaptation is recorded rather than hidden.
   */
  function viewTilesX() { return Math.round(1280 / TILE_PX / screenScale()); }
  /**
   * Visible rows, from the same table. Spec §1.2 L31-33 gives the vertical field as
   * 22.5 / 11.25 / 7.5 tiles at zoom 1 / 2 / 3, on a logical height of 720 px.
   *
   * THE CORRIDOR IS 40 ROWS AND THE DEFAULT WINDOW IS 11.25, so the camera MUST follow
   * vertically — 28.75 rows of world are off screen at zoom 2 by the spec's own numbers.
   * (This is also why the spec puts "interiors never scroll" as a HARD RULE at L35: an
   * interior template is <= 16x10 and fits, so that rule is about interiors, not about
   * the street.) A first cut of this file showed all 40 rows at once instead, which made
   * a 1280x2560 canvas whose browser-scaled reduction was an unreadable sliver — correct
   * arithmetic, useless artefact.
   *
   * At zoom 1 all 40 rows fit (22.5 x ... the pano view is static and shows the block),
   * so the camera is pinned there; at zoom 2 and 3 it follows.
   */
  function viewTilesY() { return Math.min(H, Math.max(1, Math.round(720 / TILE_PX / screenScale()))); }

  /* --- THE ASSET INTERFACE ---------------------------------------------
     A cell is rendered by cellPixelSource(cellX, cellY), which returns either
       { width, height, data }   raw RGBA bytes, width/height = TILE_PX, or
       null                      -> fall back to the procedural colour below.
     Nothing else in the render loop needs to change when real tiles arrive: the
     provider is the seam, and it is deliberately the ONLY one.

     Why raw RGBA and not an img/PNG: the page is opened from file://, where a
     canvas may not draw an image it did not originate (the canvas is tainted) and
     where fetch of a sibling file is refused. So a tile must arrive as PIXELS —
     an asset build step decodes the PNG and inlines the bytes. That is a
     consequence of the offline single-file constraint, not a preference.

     It is null today: §6.3 of the SOW records ZERO art assets in the repository. */
  var TILE_ASSETS = null;
  function cellPixelSource(cellX, cellY) {
    if (!TILE_ASSETS) return null;
    var key = cellX + ',' + cellY;
    return Object.prototype.hasOwnProperty.call(TILE_ASSETS, key) ? TILE_ASSETS[key] : null;
  }

  /**
   * The top row of the window. Pinned at zoom 1 (all 40 rows fit); follows the walker
   * otherwise, because the spec's default window is 11.25 rows and the corridor is 40.
   * Centred on the walker and clamped to the world, which is the deterministic core of
   * the follow; the spec also asks for a deadzone and lerp 0.1, and those are smoothing
   * and therefore belong with the rest of the interaction design rather than here.
   */
  function camTop() {
    var spanY = viewTilesY();
    if (spanY >= H) return 0;
    var top = walker.row - Math.floor(spanY / 2);
    if (top < 0) top = 0;
    if (top > H - spanY) top = H - spanY;
    return top;
  }
  function camLeft() {
    var span = viewTilesX();
    var left = walker.x - Math.floor(span / 2);
    if (left < 0) left = 0;
    if (left > W - span) left = W - span;
    return left;
  }

  var cv = document.getElementById('c');
  var ctx = cv.getContext('2d');
  var img = null;

  function paint() {
    var S = scale();
    var span = viewTilesX();
    var left = camLeft();
    var top = camTop();
    var spanY = viewTilesY();
    var pw = span * S, ph = spanY * S;
    if (cv.width !== pw || cv.height !== ph) {
      cv.width = pw; cv.height = ph;
      img = ctx.createImageData(pw, ph);
    }
    var d = img.data;
    var si = Math.round(S);            // integer blit size so tiles never half-pixel
    for (var ty = 0; ty < spanY; ty++) {
      var r = top + ty;
      for (var tx = 0; tx < span; tx++) {
        var x = left + tx;
        var i = (r >= 0 && r < H && x >= 0 && x < W) ? r * W + x : -1;
        var R, G, B;
        if (i < 0) { R = 255; G = 255; B = 255; }
        else if (collision[i]) { R = 60; G = 56; B = 62; }
        else if (ground[i]) { R = 214; G = 208; B = 194; }
        else { R = 246; G = 242; B = 234; }
        if (i >= 0 && !collision[i] && heights[i] > 0) {
          R = 226 - Math.min(60, heights[i] * 2); G = 232 - Math.min(50, heights[i]); B = 210;
        }
        var art = cellPixelSource(x, r);
        var y0 = ty * si, x0 = tx * si;
        for (var oy = 0; oy < si; oy++) {
          var pyy = y0 + oy;
          if (pyy >= ph) break;
          var rowBase = (pyy * pw + x0) * 4;
          for (var ox = 0; ox < si; ox++) {
            var pxx = x0 + ox;
            if (pxx >= pw) break;
            var o = rowBase + ox * 4;
            if (art) {
              // sample the 32x32 source; nearest-neighbour, which is what pixel art wants
              var sx = Math.min(art.width - 1, Math.floor((ox * art.width) / si));
              var sy = Math.min(art.height - 1, Math.floor((oy * art.height) / si));
              var so = (sy * art.width + sx) * 4;
              d[o] = art.data[so]; d[o + 1] = art.data[so + 1]; d[o + 2] = art.data[so + 2];
              d[o + 3] = art.data[so + 3];
            } else {
              d[o] = R; d[o + 1] = G; d[o + 2] = B; d[o + 3] = 255;
            }
          }
        }
      }
    }
    // doors inside the window: a red tile plus a stem toward the street.
    // Markers are drawn at integer blit size so a door is exactly one cell.
    var si2 = Math.round(S);
    for (var k = 0; k < PAYLOAD.doors.length; k++) {
      var dr = PAYLOAD.doors[k];
      var dx0 = Math.round((dr.cellX - left) * S), dy0 = Math.round((dr.cellY - top) * S);
      if (dx0 < -si2 || dy0 < -si2 || dx0 > pw || dy0 > ph) continue;
      for (var yy = 0; yy < si2; yy++) for (var xx = 0; xx < si2; xx++) {
        var px2 = dx0 + xx, py2 = dy0 + yy;
        if (px2 < 0 || py2 < 0 || px2 >= pw || py2 >= ph) continue;
        var oo = (py2 * pw + px2) * 4;
        d[oo] = 200; d[oo + 1] = 30; d[oo + 2] = 30; d[oo + 3] = 255;
      }
      var dir = Math.sign(dr.cellY - dr.streetRow) || 1;
      for (var t = 1; t <= 2; t++) for (var sy = 0; sy < si2; sy++) {
        var pxx = dx0 + ((si2 - 1) >> 1), pyy = Math.round((dr.cellY + dir * t - top) * S) + sy;
        if (pxx < 0 || pyy < 0 || pxx >= pw || pyy >= ph) continue;
        var o3 = (pyy * pw + pxx) * 4;
        d[o3] = 220; d[o3 + 1] = 120; d[o3 + 2] = 120; d[o3 + 3] = 255;
      }
    }
    ctx.putImageData(img, 0, 0);
    // the street's own centreline, the thing the walker follows
    ctx.strokeStyle = '#1F6B3A'; ctx.lineWidth = 1.5; ctx.beginPath();
    var started = false;
    for (var x2 = left; x2 <= left + span; x2++) {
      if (x2 < 0 || x2 >= W) continue;
      var row = SIM.streetRowAt(PAYLOAD.street.profile, PAYLOAD.halfCrossTiles, x2);
      if (row === null) continue;
      var cx = (x2 - left) * S + S / 2, cy = (row - top) * S + S / 2;
      if (!started) { ctx.moveTo(cx, cy); started = true; } else ctx.lineTo(cx, cy);
    }
    ctx.stroke();
    // trail + walker
    ctx.fillStyle = 'rgba(31,107,58,.30)';
    for (var i2 = 0; i2 < trail.length; i2++) {
      var tr = trail[i2];
      if (tr.x < left || tr.x > left + span) continue;
      ctx.fillRect((tr.x - left) * S, (tr.row - top) * S, S, S);
    }
    ctx.fillStyle = '#1F6B3A';
    ctx.fillRect((walker.x - left) * S + 1, (walker.row - top) * S + 1, S - 2, S - 2);
  }

  /* --- the walker --------------------------------------------------- */
  var walker = { x: PAYLOAD.walk.path.length ? PAYLOAD.walk.path[0].x : 0, row: PAYLOAD.walk.path[0].row };
  var trail = [];
  var refusals = 0;

  /** Try one step. Refuses if the destination is blocked — that IS the collision test. */
  function step(dx, dr) {
    var nx = walker.x + dx, nr = walker.row + dr;
    if (SIM.isBlocked(collision, nx, nr, W, H)) { refusals++; update(); return false; }
    walker.x = nx; walker.row = nr;
    trail.push({ x: nx, row: nr });
    if (trail.length > 2000) trail.shift();
    update();
    return true;
  }

  var KEYS = {
    ArrowRight: [1, 0], ArrowLeft: [-1, 0], ArrowUp: [0, -1], ArrowDown: [0, 1],
    d: [1, 0], a: [-1, 0], w: [0, -1], s: [0, 1]
  };
  window.addEventListener('keydown', function (e) {
    if (e.key === '[') { zoomIdx = Math.max(0, zoomIdx - 1); update(); e.preventDefault(); return; }
    if (e.key === ']') { zoomIdx = Math.min(ZOOM_LEVELS.length - 1, zoomIdx + 1); update(); e.preventDefault(); return; }
    var lower = e.key && e.key.toLowerCase ? e.key.toLowerCase() : e.key;
    if (lower === 'e') { openNearestDoor(); e.preventDefault(); return; }
    var k = KEYS[e.key] || KEYS[lower];
    if (!k) return;
    e.preventDefault();
    step(k[0], k[1]);
  });

  /* --- the interaction -------------------------------------------------
     "Open" means: a door within reach of the walker. The outcome is decided by
     SIM.openDoor against the DECLARATION in PAYLOAD.openerContract — not by the
     collision layer, and not here. */
  function nearestDoor() {
    var best = null, bestD = null;
    for (var i = 0; i < PAYLOAD.doors.length; i++) {
      var d = PAYLOAD.doors[i];
      var dist = Math.abs(d.cellX - walker.x) + Math.abs(d.cellY - walker.row);
      if (bestD === null || dist < bestD) { bestD = dist; best = d; }
    }
    return bestD !== null && bestD <= 3 ? best : null;
  }

  var lastInteraction = null;

  function openNearestDoor() {
    var d = nearestDoor();
    if (!d) { lastInteraction = null; renderPanel('no door within reach', null); return; }
    var outcome = SIM.openDoor(d.doorId, PAYLOAD.openerContract, PAYLOAD);
    lastInteraction = outcome;
    renderPanel(null, outcome);
  }

  /**
   * The panel. This is where the north/south distinction has to be legible to
   * someone who knows nothing about the project.
   *
   * A MODELLED surface prints an annotation that states only what was measured.
   * An UNMODELLED surface prints the placeholder and NOTHING ELSE about the inside,
   * and no diagram is drawn for it: an absent diagram is honest, an invented one is
   * the defect the card forbids.
   */
  function renderPanel(message, o) {
    var el = document.getElementById('panel');
    if (message) { el.className = 'panel'; el.innerHTML = '<b>' + message + '</b>'; return; }
    if (!o) { el.className = 'panel'; el.innerHTML = ''; return; }
    var html = '';
    html += '<div class="ph-title">' + esc(o.doorId) + ' · ' + esc(o.title) + '</div>';
    if (o.placeholder) {
      // THE placeholder. One string, and the note says plainly that no layout is shown.
      html += '<div class="ph-flag">' + esc(o.placeholder) + '</div>';
      html += '<div class="ph-note">' + esc(o.placeholderNote) + '</div>';
      html += '<div class="ph-note">' + esc(o.kind) + ' — the shopfront exists in the world; this version has no interior for it, so nothing is drawn.</div>';
    } else if (o.annotation) {
      html += '<div class="ok-flag">measured interior</div>';
      html += '<div class="ph-note">' + esc(o.annotation) + '</div>';
      html += '<div class="ph-note">' + esc(o.annotationZh || '') + '</div>';
      if (o.drawRoom) {
        // The ONLY thing drawn for a real room: its measured extent, 1 px per row, with
        // a hatch marking the back wall. No furniture, no plan, no invented layout.
        html += '<canvas id="room" width="' + (o.measuredInteriorRows * 24 + 2) + '" height="26"></canvas>';
        html += '<div class="ph-note">the hatched strip is ' + o.measuredInteriorRows + ' row(s) deep — this is the room\\'s MEASURED EXTENT, not a floor plan</div>';
      }
    } else {
      html += '<div class="ph-flag">' + esc(o.kind) + '</div>';
    }
    el.className = 'panel';
    el.innerHTML = html;
    if (o.drawRoom && o.measuredInteriorRows) drawRoomStrip(o.measuredInteriorRows);
  }

  function drawRoomStrip(rows) {
    var rc = document.getElementById('room');
    if (!rc || !rc.getContext) return;
    var g = rc.getContext('2d');
    if (!g) return;
    g.fillStyle = '#e8f0e8'; g.fillRect(0, 0, rc.width, rc.height);
    g.fillStyle = '#1F6B3A'; g.fillRect(0, 0, 2, rc.height);            // doorway
    g.fillStyle = '#cfe0cf'; g.fillRect(2, 4, rows * 24, rc.height - 8); // the measured extent
    g.fillStyle = '#16161D';                                            // the back wall, hatched
    for (var x = 2 + rows * 24; x < 2 + rows * 24 + 6 && x < rc.width; x += 2) g.fillRect(x, 0, 1, rc.height);
  }

  function esc(s) {
    return String(s === null || s === undefined ? '' : s)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  }

  function update() {
    paint();
    document.getElementById('pos').textContent =
      'x=' + walker.x + ' of ' + (W - 1) + '  ·  row ' + walker.row + ' of ' + (H - 1) +
      '  ·  along-street ' + walker.x + ' m  ·  zoom ' + zoomLevel() +
      ' (' + scale() + ' screen px/tile, ' + viewTilesX() + ' tiles wide)' +
      '  ·  steps ' + trail.length + '  ·  refused (wall) ' + refusals +
      '  ·  this tile collision=' + collision[walker.row * W + walker.x];
  }

  /* --- the overlay the assertions describe --------------------------- */
  var enterable = 0, reachable = 0, withRoom = 0;
  var rows = ['<table><tr><th>door</th><th>cell</th><th>street row</th><th>reachable</th><th>surface</th><th>free depth behind</th><th>what opening it gives you</th><th>guide place</th></tr>'];
  for (var q = 0; q < PAYLOAD.doors.length; q++) {
    var d2 = PAYLOAD.doors[q];
    if (d2.reachable) reachable++;
    if (d2.interaction && d2.interaction.drawRoom) withRoom++;
    if (d2.interaction && d2.interaction.placeholder) enterable++;
    var gives = d2.interaction
      ? (d2.interaction.drawRoom ? 'a modelled interior (' + d2.interaction.measuredInteriorRows + ' rows)'
                                 : '<span class="warn">placeholder: ' + d2.interaction.placeholder + '</span>')
      : '<span class="dim">no declaration</span>';
    rows.push('<tr><td>' + d2.doorId + '</td><td>' + d2.cellX + ',' + d2.cellY + '</td><td>' + d2.streetRow +
      '</td><td>' + (d2.reachable ? 'yes' : 'no') + '</td><td>' + (d2.surface || '—') +
      '</td><td>' + d2.depthBehind + '</td><td>' + gives + '</td><td>' +
      (d2.placeNameJa || d2.placeId || '<span class="dim">—</span>') + '</td></tr>');
  }
  rows.push('</table>');
  document.getElementById('legend').innerHTML =
    '<p><b>walk</b>: reached x=' + PAYLOAD.walk.reachedX + ' of ' + (W - 1) +
    ' in ' + PAYLOAD.walk.steps + ' steps, ' + PAYLOAD.walk.corrections + ' row correction(s); rows ' +
    PAYLOAD.walk.startRow + ' → ' + PAYLOAD.walk.endRow + '.' +
    ' The street drifts ' + PAYLOAD.street.driftSpanM + ' m, so the walker follows the profile, not a fixed row.</p>' +
    '<p><b>doors</b>: ' + PAYLOAD.doors.length + ' doors, all openable · ' + reachable + ' of ' +
    PAYLOAD.doors.length + ' reachable from the street · ' + withRoom + ' of ' + PAYLOAD.doors.length +
    ' open into a modelled interior · ' + enterable + ' of ' + PAYLOAD.doors.length +
    ' are <span class="warn">placeholder only</span>. ' +
    'Every door is enterable after the ruling; what differs is whether an interior is MODELLED behind it. ' +
    'Press <b>E</b> at a door to see which you are at. The doors are <code>authored</code>: nobody has observed them.</p>' +
    '<p><b>export</b>: ' + PAYLOAD.guide.placeCount + ' place ids reconciled from ' + PAYLOAD.guide.path +
    ' (' + PAYLOAD.guide.stopCount + ' route stops + ' + PAYLOAD.guide.nearbyCount + ' passed alongside).</p>' +
    rows.join('');
  update();

  // expose for a headless probe, and for a curious person with a console
  window.__TG = { walker: walker, step: step, refusals: function () { return refusals; },
                  SIM: SIM, collision: collision, isBlocked: SIM.isBlocked, W: W, H: H,
                  zoom: function () { return zoomLevel(); }, camLeft: camLeft,
                  tilePx: TILE_PX, screenPxPerTile: scale, viewTilesX: viewTilesX,
                  hasTileAssets: function () { return TILE_ASSETS !== null; },
                  openNearestDoor: openNearestDoor, nearestDoor: nearestDoor,
                  lastInteraction: function () { return lastInteraction; },
                  openerContract: PAYLOAD.openerContract };
})();
</script>
</body>
</html>
`;

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(OUT, html, 'utf8');

const sha = sha256Hex(Buffer.from(html, 'utf8'));
/**
 * Report the two numbers as the two different things they are. "7/10 enterable" was
 * the old phrasing and the ruling made it false: every door is enterable now, and what
 * differs is whether an interior is MODELLED behind it.
 */
const placeholderOnly = doorMarkers.filter((d) => d.interaction && d.interaction.placeholder).length;
const modelled = doorMarkers.filter((d) => d.interaction && d.interaction.drawRoom).length;
const reachableCount = doorMarkers.filter((d) => d.reachable).length;

const out = [];
out.push('bake-viewer — the walkable shell');
out.push(`  scene      : ${SCENE_SHA}  (${buf.length} B, ${W}x${H})`);
out.push(`  contract   : ${payload.scene.contractHash}`);
out.push(`  guide      : ${payload.guide.placeCount} place ids reconciled (${payload.guide.stopCount} stops + ${payload.guide.nearbyCount} alongside)`);
out.push(`  street     : drift ${payload.street.driftSpanM} m · rows ${payload.walk.startRow} -> ${payload.walk.endRow}`);
out.push(`  walk       : reached x=${payload.walk.reachedX} of ${W - 1} in ${payload.walk.steps} steps, ${payload.walk.corrections} correction(s)`);
out.push(`  doors      : ${doorMarkers.length} total, all openable · ${reachableCount} reachable from the street · ` +
  `${modelled} open into a modelled interior · ${placeholderOnly} placeholder only`);
out.push(`  simulation : ${simSource.length} B serialised out of check-viewer.mjs (same bodies, not a copy)`);
out.push(`  page       : ${OUT}`);
out.push(`               ${html.length} B, single file, no network`);
out.push(`               sha256 ${sha}`);
out.push('');
out.push(`  open it    : Start-Process "${OUT}"      (Windows)`);
out.push(`               open "${OUT}"               (macOS)`);
out.push(`               xdg-open "${OUT}"           (Linux)`);
out.push('  no server is needed: every layer is inlined, so file:// works.');
process.stdout.write(`${out.join('\n')}\n`);
process.exitCode = 0;
