#!/usr/bin/env node
/**
 * bake-viewer.mjs — build `iteration/viewer/index.html`: the walkable shell.
 *
 * WHAT IT EMITS, AND WHY IT IS ONE FILE
 * -------------------------------------
 * A single self-contained HTML page with no network access of any kind. That is
 * not tidiness, it is the requirement: Chrome and Firefox refuse to load a module
 * script from `file://` (it is treated as a CORS request), and even a classic
 * `<script src="…">` is refused. A viewer that needs `python -m http.server`
 * before it opens is a viewer someone has to explain, and Gate 1's criterion is
 * that ONE REAL PERSON walks it. So the four layers, the manifest, the street
 * profile, the doors and the walker are all inlined.
 *
 * THE WALKER ON THE PAGE IS NOT A COPY
 * ------------------------------------
 * The simulation functions are serialised out of `check-viewer.mjs` with
 * `.toString()` and re-evaluated in the page. The browser therefore runs the same
 * function BODIES that the headless assertions check. A hand-written second copy
 * would be a second source of truth, and this project has already paid for one of
 * those (D-12: the valueKind enum mirrored into doors.json went stale).
 *
 * The layers ship as base64 because the payload has to survive living inside a
 * `<script>` tag. The obvious optimisation — one JSON object with a small numeric
 * alphabet — needs a character like `<` or a quote in that alphabet and then the
 * payload can terminate the tag early. Base64's alphabet is [A-Za-z0-9+/=], which
 * cannot appear in `</script>`, and the trailing `=` padding is trimmed here and
 * restored on decode.
 *
 * USAGE
 *   node iteration/tools/bake-viewer.mjs            bake
 *   node iteration/tools/bake-viewer.mjs --bake-if-absent   bake scene.bin first
 *
 * Exit codes: 0 = baked, 1 = a problem, 2 = environment (no scene.bin).
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { SCENE_VERSION, SCENE_MAGIC } from './emit-scene.mjs';
import { join, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';

import {
  walkStreet, doorReport, reachableSet, streetRowAt, frameHashInput, isBlocked, idx,
  serialiseSimulation, sha256Hex,
} from './check-viewer.mjs';
import { openDoor } from './viewer-interaction.mjs';

const REPO = resolve(import.meta.dirname, '..', '..');
const SCENE = join(REPO, 'build', 'scene.bin');
const GUIDE = join(REPO, 'build', 'guide.json');
/**
 * `--doors <path>` and `--opener <path>` are FIRE-DRILL overrides, the same shape as
 * `validate-doors.mjs --doors`: bake a variant against an alternate fact layer so the
 * assertions can be shown to follow their inputs. `--out <dir>` keeps the drill away
 * from the shipped page, because a demonstration that can overwrite the artefact is
 * not a drill.
 */
const DOORS = (() => {
  const i = process.argv.indexOf('--doors');
  return i >= 0 && process.argv[i + 1]
    ? resolve(process.argv[i + 1])
    : join(REPO, 'city-packs', 'kyoto-shijo', 'doors.json');
})();
/**
 * The DECLARATION of which doors are openable and what kind of surface each has.
 * Generated by `build-opener-fact.mjs`; this baker consumes it and never decides it.
 */
const OPENER = (() => {
  const i = process.argv.indexOf('--opener');
  return i >= 0 && process.argv[i + 1]
    ? resolve(process.argv[i + 1])
    : join(REPO, 'iteration', 'viewer', 'opener-contract.json');
})();
/**
 * `--out <dir>` exists so a FIRE DRILL can bake a variant somewhere else and run the
 * checks against it. The demonstration the task card asks for — point the checks at a
 * 9-door input and show the assertions FOLLOW rather than redden — must not be able to
 * touch the shipped page, or the drill becomes the incident.
 */
const OUT_DIR = (() => {
  const i = process.argv.indexOf('--out');
  return i >= 0 && process.argv[i + 1] ? resolve(process.argv[i + 1]) : join(REPO, 'iteration', 'viewer');
})();
const OUT = join(OUT_DIR, 'index.html');

const { worldGrid, GRID, ORIGIN, quantizeToSubTile, locateSubTile } = await import(
  new URL('../../docs/handOff/dsh-bundle-tourguide-2.5d/tools/world-grid.mjs', import.meta.url).href
);

function die(code, msg) {
  process.stderr.write(`${msg}\n`);
  process.exit(code);
}

/* ------------------------------------------------------------------ *
 * Read the scene. FAIL LOUDLY: build/ is gitignored, so a clean clone has
 * no scene.bin and this must say exactly what to run rather than emit a
 * page that silently renders nothing.
 * ------------------------------------------------------------------ */
if (!existsSync(SCENE)) {
  if (!process.argv.includes('--bake-if-absent')) {
    die(2,
      `no scene.bin at ${SCENE}\n` +
      `  build/ is gitignored, so a clean clone has none.\n` +
      `  run: node iteration/tools/emit-scene.mjs    (or pass --bake-if-absent)`);
  }
  const r = spawnSync(process.execPath, [join(REPO, 'iteration', 'tools', 'emit-scene.mjs')], { cwd: REPO, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
  if (r.status !== 0) die(2, `could not bake the scene (exit ${r.status}): ${((r.stdout || '') + (r.stderr || '')).slice(-500)}`);
}
if (!existsSync(GUIDE)) {
  die(2,
    `no guide.json at ${GUIDE}\n` +
    `  the walk must be reconciled against the game's EXPORT, and the export is guide.json.\n` +
    `  run: node iteration/tools/emit-guide.mjs`);
}
if (!existsSync(OPENER)) {
  die(2,
    `no opener-contract.json at ${OPENER}\n` +
    `  which doors are openable, and of what kind, is a FACT-LAYER DECLARATION; this baker\n` +
    `  consumes it and does not decide it. It is generated, not hand-written:\n` +
    `  run: node iteration/tools/build-opener-fact.mjs`);
}

const buf = readFileSync(SCENE);
const W = buf.readUInt32LE(12);
const H = buf.readUInt32LE(16);
const manifestLen = buf.readUInt32LE(104);
const manifest = JSON.parse(buf.toString('utf8', 108, 108 + manifestLen));
const o = 108 + manifestLen;
const n = W * H;
const ground = buf.subarray(o, o + n);
const collision = buf.subarray(o + n, o + 2 * n);
const heights = buf.subarray(o + 2 * n, o + 3 * n);
const occlusionHalf = buf.subarray(o + 3 * n, o + 3 * n + W);
const openings = buf.subarray(o + 3 * n + W, o + 4 * n + W);

// Re-assert the container here rather than trusting it: this baker is a fourth
// reader, and a fourth reader that assumes is a fourth chance to be wrong.
if (buf.toString('ascii', 0, 8) !== SCENE_MAGIC || buf.readUInt32LE(8) !== SCENE_VERSION ||
    W !== worldGrid.wTiles || H !== worldGrid.hTiles ||
    108 + manifestLen + (n * 4 + W) !== buf.length) {
  die(1, `scene.bin does not match the frozen contract header (${W}x${H}, manifest ${manifestLen}, ${buf.length} B)`);
}

const SCENE_SHA = sha256Hex(buf);
const profile = manifest.street ? manifest.street.profile : null;
if (!profile) die(1, 'scene manifest carries no street.profile — the walker cannot know where the street is');

const doorsFile = JSON.parse(readFileSync(DOORS, 'utf8'));
const doors = doorsFile.doors;
const guide = JSON.parse(readFileSync(GUIDE, 'utf8'));
const opener = JSON.parse(readFileSync(OPENER, 'utf8'));

/* ------------------------------------------------------------------ *
 * Run the walk and the door analysis HERE, so the page opens showing a
 * correct, already-verified state instead of an empty canvas.
 * ------------------------------------------------------------------ */
const reached = reachableSet(collision, W, H, 0);
const walk = walkStreet(profile, collision, W, H, GRID.halfCrossTiles, {});
const doorsReport = doorReport(doors, profile, collision, W, H, GRID.halfCrossTiles, reached);

const placeById = new Map();
for (const s of [...guide.stops, ...guide.nearby]) placeById.set(s.placeId, s);
// doors.json names its building by OSM way; the bridge to the export is the fact
// layer's entrances.doorIds (the same bridge check-viewer.mjs V5 walks).
const placesFile = JSON.parse(readFileSync(join(REPO, 'city-packs', 'kyoto-shijo', 'places.json'), 'utf8'));
const doorToPlace = new Map();
for (const p of placesFile) {
  if (!p.entrances || !Array.isArray(p.entrances.doorIds)) continue;
  for (const id of p.entrances.doorIds) doorToPlace.set(id, p.id);
}

const doorMarkers = doorsReport.map((d) => {
  const placeId = doorToPlace.get(d.doorId) || null;
  const place = placeId ? placeById.get(placeId) : null;
  /**
   * The interaction is RESOLVED HERE, by the same `openDoor` body the page and the
   * assertions both use — so what the page shows is what was checked, and the page
   * never re-derives it. `surface` comes from the declaration, never from `depthBehind`.
   */
  const declared = (opener.openable || []).find((o) => o.doorId === d.doorId) || null;
  const interaction = openDoor(d.doorId, opener, { doors: doorsReport });
  return {
    ...d,
    placeId,
    placeNameJa: place ? place.nameJa : null,
    inGuide: Boolean(place),
    openable: declared ? declared.openable : false,
    surface: declared ? declared.surface : null,
    interaction,
  };
});

/* ------------------------------------------------------------------ *
 * Layers -> base64 with trailing '=' trimmed ('=' cannot be trusted to
 * survive some editors; the length is in the payload, so it is restored).
 * ------------------------------------------------------------------ */
const b64 = (view) => Buffer.from(view).toString('base64').replace(/=+$/, '');

const payload = {
  schema: 'tourguide.viewer-scene/v1',
  scene: {
    path: 'build/scene.bin',
    sha256: SCENE_SHA,
    bytes: buf.length,
    grid: { wTiles: W, hTiles: H },
    chunksAlongX: buf.readUInt32LE(20),
    origin: { lonUdeg: ORIGIN.lonUdeg, latUdeg: ORIGIN.latUdeg },
    contractHash: buf.toString('ascii', 40, 104),
  },
  halfCrossTiles: GRID.halfCrossTiles,
  street: { driftSpanM: manifest.street.driftSpanM, profile },
  layers: {
    encoding: 'base64, trailing = trimmed',
    byteLengths: { ground: n, collision: n, heights: n, occlusionHalf: W, openings: n },
    ground: b64(ground),
    collision: b64(collision),
    heights: b64(heights),
    occlusionHalf: b64(occlusionHalf),
    openings: b64(openings),
  },
  /**
   * The DECLARATION travels into the page, and so does the interaction source. The page
   * consumes them; it does not decide which doors are openable, and it does not carry a
   * second copy of the placeholder string.
   */
  openerContract: {
    schema: opener.schema,
    generatedBy: opener.generatedBy,
    surfaceKinds: opener.surfaceKinds,
    modelRule: opener.modelRule,
    counts: opener.counts,
    openable: opener.openable,
  },
  doors: doorMarkers,
  walk: {
    reachedX: walk.reachedX,
    steps: walk.steps,
    corrections: walk.corrections,
    stoppedAt: walk.stoppedAt,
    startRow: walk.path.length ? walk.path[0].row : null,
    endRow: walk.path.length ? walk.path[walk.path.length - 1].row : null,
    path: walk.path,
  },
  guide: {
    path: 'build/guide.json',
    schema: guide.schema,
    stopCount: guide.stops.length,
    nearbyCount: guide.nearby.length,
    placeCount: guide.stops.length + guide.nearby.length,
    // only what the overlay needs, so the page cannot become a second export
    stops: guide.stops.map((s) => ({ seq: s.seq, placeId: s.placeId, nameJa: s.nameJa, nameZh: s.nameZh, alongStreetM: s.alongStreetM })),
  },
  /**
   * THE TWO VARIANTS. V-A is bare (no instructional text at all), V-B adds a keymap
   * that says ONLY which keys move — no goal, no colour legend. They exist to separate
   * the third cause of "nothing happens": the keys may simply not be discoverable. A
   * keymap that also explained the goal would confound that, so it does not.
   */
  variants: {
    'V-A': { id: 'V-A', label: 'bare', keymap: false, instructionalText: [] },
    'V-B': { id: 'V-B', label: 'keymap', keymap: true, instructionalText: ['keymap: arrows or WASD move · E opens the door you stand at'] },
  },
  defaultVariant: 'V-A',
};

/* ------------------------------------------------------------------ *
 * THE ANCHORS — the pure-function target set for `next` (play-systems.md §1.7)
 *
 * `anchors := guide.json's inSceneWindow records ∪ doors.json's doorways`, each with a
 * real name, a cell, per-field provenance and a source. Nothing here is invented: the
 * name and its valueKind come from guide.json's cells, the source URL from the same
 * cell, and the CELL is computed by the contract's own quantiser — quantizeToSubTile +
 * locateSubTile — NOT by rounding.
 *
 * That last point is a correction worth recording: `cellX = round(alongStreetM)` looked
 * obvious and DISAGREED with guide.json on 3 of its 4 recorded tiles (e.g. 四条河原町
 * バス停D: round gives row 16, the contract's quantiser gives row 15). The quantiser
 * reproduced all four exactly. A second, plausible-looking conversion was wrong.
 * ------------------------------------------------------------------ */
function cellOf(alongStreetM, acrossStreetM) {
  const sub = quantizeToSubTile(alongStreetM, acrossStreetM);
  const at = locateSubTile(sub.subX, sub.subY);
  return { cellX: at.tileX, cellY: at.row, subX: sub.subX, subY: sub.subY, inWindow: at.inWindow };
}

const placeByAnchorId = new Map();
for (const p of placesFile) placeByAnchorId.set(p.id, p);

function cellsFromGuideRow(r) {
  const all = [...(r.verified || []), ...(r.otherKinds || [])];
  const nameCell = all.find((c) => c.field === r.nameFieldUsed) || all.find((c) => c.field === 'nameJa') || null;
  return {
    nameFieldKind: nameCell ? nameCell.valueKind : null,
    sourceUrl: nameCell ? nameCell.sourceUrl : null,
    verifiedFields: (r.verified || []).map((c) => ({ field: c.field, value: c.value, valueKind: c.valueKind, sourceUrl: c.sourceUrl })),
  };
}

const ANCHORS = [];
for (const r of [...guide.stops, ...guide.nearby]) {
  if (!r.inSceneWindow) continue;
  const p = placeByAnchorId.get(r.placeId) || null;
  const c = cellOf(r.alongStreetM, r.acrossStreetM);
  const cells = cellsFromGuideRow(r);
  ANCHORS.push({
    kind: 'place',
    id: r.placeId,
    nameJa: r.nameJa,
    nameZh: r.nameZh || null,
    alongStreetM: r.alongStreetM,
    acrossStreetM: r.acrossStreetM,
    cellX: c.cellX,
    cellY: c.cellY,
    nameFieldKind: cells.nameFieldKind,
    modelled: true,   // a real place with a source: always eligible to be named
    verifiedFields: cells.verifiedFields,
    sourceUrl: cells.sourceUrl || (p ? p.source_url : null),
    verifiedAt: p ? p.verified_at : null,
  });
}
for (const d of doorMarkers) {
  ANCHORS.push({
    kind: 'doorway',
    id: d.doorId,
    nameJa: d.placeNameJa || d.doorId,
    nameZh: null,
    alongStreetM: d.cellX,
    acrossStreetM: d.cellY - GRID.halfCrossTiles,
    cellX: d.cellX,
    cellY: d.cellY,
    nameFieldKind: 'authored',
    verifiedFields: [],
    sourceUrl: null,
    verifiedAt: null,
    surface: d.surface,
    openable: d.openable,
    /**
     * The spec's `modelled` flag, and it is the one that decides whether this door can be
     * NAMED as the next target (§1.7's `eligible`). `modelled: false` means the shopfront
     * is real but this engine has no interior geometry behind it — a placeholder door.
     *
     * It is still drawn, still enterable, still counted in 门洞 n/10. Only the pointing is
     * gated. Without this clause the target sequence walks the player through three
     * 「内容开发中」 doors in a row, because they sit in a 7 m chain on row 0.
     */
    modelled: d.surface !== 'unmodelled-interior',
  });
}
// deterministic order, so `next`'s tie-break is reproducible rather than incidental
ANCHORS.sort((a, b) => (a.alongStreetM - b.alongStreetM) || (a.id < b.id ? -1 : 1));

/**
 * Attached after construction rather than inside the literal, because `ANCHORS` is built
 * from `doorMarkers` and the contract's quantiser and therefore cannot be referenced above.
 * A `const` in the temporal dead zone throws; a property assignment here cannot.
 *
 * `guideCounts` carries S2's three denominators so the page computes all three from input.
 * Spec §1.4 is explicit about why: this repository has already gone red twice for a
 * hardcoded door count (task-23), so a literal denominator is a known defect shape.
 */
payload.anchors = ANCHORS;
payload.guideCounts = {
  placeTotal: guide.stops.length + guide.nearby.length,
  placeInWindow: ANCHORS.filter((a) => a.kind === 'place').length,
  doorwayTotal: ANCHORS.filter((a) => a.kind === 'doorway').length,
};

/* ------------------------------------------------------------------ *
 * The page. Plain HTML + one classic <script>. No imports, no fetch.
 * ------------------------------------------------------------------ */
const simSource = serialiseSimulation();

const html = `<!DOCTYPE html>
<html lang="zh-Hans">
<head>
<meta charset="utf-8">
<title>四条通 — walkable shell (Gate 1)</title>
<style>
  :root { --ink:#16161D; --paper:#F6F2EA; --ok:#1F6B3A; --warn:#8A5A00; --unknown:#6B6B6B; }
  * { box-sizing: border-box; }
  body { margin:0; background:var(--paper); color:var(--ink);
         font:13px/1.45 ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; }
  header { padding:9px 14px; border-bottom:1px solid #d8d2c4; display:flex; gap:16px; flex-wrap:wrap; align-items:baseline; }
  header h1 { font-size:15px; margin:0; font-weight:700; }
  header .k { color:var(--unknown); }
  #hud { background:rgba(246,242,234,.95); padding:6px 14px; border-bottom:1px solid #d8d2c4; }
  .pill { display:inline-block; padding:1px 6px; border:1px solid #d8d2c4; border-radius:2px; margin-right:6px; }
  .ok { color:var(--ok); } .warn { color:var(--warn); } .dim { color:var(--unknown); }
  #scroll { padding:12px 14px; }
  canvas { display:block; border:1px solid #d8d2c4; background:#fff; max-width:100%; }
  /* ---- the four HUD slots (play-systems.md §1.4). Only four. ---- */
  #hud { display:flex; gap:22px; flex-wrap:wrap; align-items:flex-start; padding:8px 14px 10px; }
  .slot { min-width:0; }
  .slot .lbl { color:var(--unknown); font-size:11px; letter-spacing:.06em; text-transform:uppercase; }
  .slot .val { font-size:15px; font-weight:700; white-space:nowrap; }
  /* S1 — the edge indicator. It is the only thing that carries "where and how far", so it
     is the loudest element on the page until the target enters the window. */
  #s1 { color:var(--warn); }
  #s1 .arrow { font-size:22px; line-height:1; }
  #s1 .m { font-size:17px; font-weight:700; }
  .count { font-variant-numeric:tabular-nums; }
  .count b { font-size:16px; }
  #s4 .ph-flag { display:inline-block; background:var(--warn); color:#fff; padding:2px 9px;
                 font-weight:700; letter-spacing:.04em; margin:2px 0; }
  #s4 .ok-flag { display:inline-block; background:var(--ok); color:#fff; padding:2px 9px;
                 font-weight:700; letter-spacing:.04em; margin:2px 0; }
  #s4 .t { font-weight:700; }
  #s4 .n { color:var(--unknown); font-size:12px; }
  .hidden { display:none !important; }
  #keymap { color:var(--unknown); font-size:12px; padding:0 14px 8px; }
  #log { padding:0 14px 14px; }
  #log textarea { width:100%; height:90px; font:11px/1.4 ui-monospace, monospace; }
  #logbtn { font:12px ui-monospace, monospace; }
  .panel { margin-top:0; max-width:760px; }
  .ph-note { color:var(--unknown); font-size:12px; margin:2px 0; }
</style>
</head>
<body>
<header>
  <h1>四条通</h1>
  <span><span class="k">scene</span> ${SCENE_SHA.slice(0, 12)}…</span>
  <span><span class="k">variant</span> <span id="variantLabel">V-A</span></span>
</header>
<div id="hud">
  <!-- S1 · edge indicator: direction + integer metres. Hidden the moment next is on screen. -->
  <div class="slot" id="s1"><div class="lbl">目标</div><div class="val"><span class="arrow">→</span> <span class="m"></span></div></div>
  <!-- S2 · three counters, never merged -->
  <div class="slot" id="s2"><div class="lbl">计数</div><div class="val count"></div></div>
  <!-- S3 · status readout; the name is a VALUE from the fact layer -->
  <div class="slot" id="s3"><div class="lbl">位置</div><div class="val"></div></div>
  <!-- S4 · the doorway receipt, present only while a door is open -->
  <div class="slot hidden" id="s4"></div>
</div>
<div id="keymap" class="hidden"></div>
<div id="scroll">
  <canvas id="c"></canvas>
</div>
<div id="log"><button id="logbtn">导出按键日志</button><textarea id="logtext" readonly></textarea></div>

<script id="__TG_SCENE__" type="application/json">${JSON.stringify(payload)}</script>
<script>
(function () {
  'use strict';
  var PAYLOAD = JSON.parse(document.getElementById('__TG_SCENE__').textContent);

  /* --- decode the frozen layers ------------------------------------- */
  function b64view(s, expectedLen) {
    var pad = (4 - (s.length % 4)) % 4;
    var bin = atob(s + Array(pad + 1).join('='));
    var out = new Uint8Array(bin.length);
    for (var i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
    if (expectedLen !== undefined && out.length !== expectedLen) {
      throw new Error('layer length ' + out.length + ' but the payload declares ' + expectedLen);
    }
    return out;
  }
  var W = PAYLOAD.scene.grid.wTiles, H = PAYLOAD.scene.grid.hTiles;
  var L = PAYLOAD.layers.byteLengths;
  var ground = b64view(PAYLOAD.layers.ground, L.ground);
  var collision = b64view(PAYLOAD.layers.collision, L.collision);
  var heights = b64view(PAYLOAD.layers.heights, L.heights);
  var occlusionHalf = b64view(PAYLOAD.layers.occlusionHalf, L.occlusionHalf);

  /* --- THE simulation, serialised out of check-viewer.mjs -------------
     Same function bodies the headless assertions ran against. Not a copy. */
  var SIM = ${simSource};

  /* --- the camera ----------------------------------------------------
     SCALE IS FROM THE SPEC, NOT FROM TASTE. appendix-visual-and-ui-spec.md:
       §1.1 L17  tile is 32x32 px, 1 tile = 1 m, one block = 40x40 tiles = 1280x1280 px
       §1.2 L25  zoom is an INTEGER, 1/2/3 only (non-integers make the pixels shimmer)
       §1.2 L27  logical canvas 1280x720
       §1.2 L29  zoom table: zoom 1 sees 1280 px of world = 40 tiles; zoom 2 sees 640 px
                 = 20 tiles; zoom 3 sees 426.7 px = 13.3 tiles
       §1.2 L35  every interior fits on one screen at zoom 2; interiors never scroll
       L131      "zoom 2 -> 640x360 world pixels, x2 -> 1280x720"

     => screenScale = zoom. A tile is 32 world px, so on screen it is 32 x zoom px: 32 at
        zoom 1, 64 at zoom 2, 96 at zoom 3. zoom 1 is the pano/debug view, zoom 2 is the
        default the rest of the spec assumes, zoom 3 is signboard study. L22 confirms it
        independently: a 12 px world glyph is 24 px on screen at zoom 2.

     THE FIRST VERSION OF THIS CORRECTION HAD THE RATIO INVERTED (32/zoom), which made
     zoom 2 show 80 tiles instead of 20 — it zoomed OUT where the spec zooms IN. The
     arithmetic looked plausible and my own new assertion passed, because that assertion
     had been written from the same wrong reading. What settled it was L131's "x2", not
     any table cell. A wrong reading and an assertion built on it agree with each other.

     NO BACKTICKS IN THIS BLOCK: the page's JavaScript is emitted inside a template
     literal, so a backtick here terminates it early — the same failure class as a literal
     closing script tag. */
  var TILE_PX = 32;                      // spec §1.1: one tile is 32x32 world px
  var ZOOM_LEVELS = [1, 2, 3];           // spec §1.2: integers only, non-integers shimmer
  var DEFAULT_ZOOM_INDEX = 1;            // -> zoom 2, the level the spec's rules assume
  var zoomIdx = DEFAULT_ZOOM_INDEX;

  function zoomLevel() { return ZOOM_LEVELS[zoomIdx]; }
  /** Screen pixels per WORLD pixel. Spec L131: zoom 2 maps 640 world px onto 1280. */
  function screenScale() { return zoomLevel(); }
  /** Screen pixels per tile: 32 world px, each screenScale() screen px across. */
  function scale() { return TILE_PX * screenScale(); }
  /**
   * The spec's logical width is 1280 px and its zoom table is that width over the 32
   * world px in a tile, so 1280 / 32 / zoom reproduces the table exactly: 40 / 20 / 13.3.
   * The logical HEIGHT assumes 16:9, while this corridor is 40 rows — so the HEIGHT comes
   * from the world (all 40 rows always visible, the walk is never vertically blind) and
   * the WIDTH from the spec. The adaptation is recorded rather than hidden.
   */
  function viewTilesX() { return Math.round(1280 / TILE_PX / screenScale()); }
  /**
   * Visible rows, from the same table. Spec §1.2 L31-33 gives the vertical field as
   * 22.5 / 11.25 / 7.5 tiles at zoom 1 / 2 / 3, on a logical height of 720 px.
   *
   * THE CORRIDOR IS 40 ROWS AND THE DEFAULT WINDOW IS 11.25, so the camera MUST follow
   * vertically — 28.75 rows of world are off screen at zoom 2 by the spec's own numbers.
   * (This is also why the spec puts "interiors never scroll" as a HARD RULE at L35: an
   * interior template is <= 16x10 and fits, so that rule is about interiors, not about
   * the street.) A first cut of this file showed all 40 rows at once instead, which made
   * a 1280x2560 canvas whose browser-scaled reduction was an unreadable sliver — correct
   * arithmetic, useless artefact.
   *
   * At zoom 1 all 40 rows fit (22.5 x ... the pano view is static and shows the block),
   * so the camera is pinned there; at zoom 2 and 3 it follows.
   */
  function viewTilesY() { return Math.min(H, Math.max(1, Math.round(720 / TILE_PX / screenScale()))); }

  /* --- THE ASSET INTERFACE ---------------------------------------------
     A cell is rendered by cellPixelSource(cellX, cellY), which returns either
       { width, height, data }   raw RGBA bytes, width/height = TILE_PX, or
       null                      -> fall back to the procedural colour below.
     Nothing else in the render loop needs to change when real tiles arrive: the
     provider is the seam, and it is deliberately the ONLY one.

     Why raw RGBA and not an img/PNG: the page is opened from file://, where a
     canvas may not draw an image it did not originate (the canvas is tainted) and
     where fetch of a sibling file is refused. So a tile must arrive as PIXELS —
     an asset build step decodes the PNG and inlines the bytes. That is a
     consequence of the offline single-file constraint, not a preference.

     It is null today: §6.3 of the SOW records ZERO art assets in the repository. */
  var TILE_ASSETS = null;
  function cellPixelSource(cellX, cellY) {
    if (!TILE_ASSETS) return null;
    var key = cellX + ',' + cellY;
    return Object.prototype.hasOwnProperty.call(TILE_ASSETS, key) ? TILE_ASSETS[key] : null;
  }

  /**
   * The top row of the window.
   *
   * Spec §1.5 gives the follow rule in full:
   *   dir = sign(next.cellY - walker.row)
   *   camTop = clamp(walker.row + dir*floor(spanY/3) - floor(spanY/2), 0, H-spanY)
   * so the camera is BIASED toward the target, not merely centred on the walker: the bias
   * turns "walk 8 blind steps north before a door enters the window" into 5. At spawn the
   * target is 四条烏丸交差点 on the SAME row as the walker, so dir = 0 and the bias does
   * nothing vertically — which is exactly what makes the "first frame has an anchor"
   * criterion unreachable by camera tuning, and why that criterion is written against the
   * HUD instead (see the card, §验收判据).
   *
   * lerp 0.1 is deliberately NOT implemented: the page has no frame loop, the existing
   * determinism assertion requires two renders to be byte-identical, and 1 key = 1 cell is
   * already discrete — interpolation would only add smoke to a discrete action.
   * The deadzone is integer cells (spec §1.5: 3 x 2 at zoom 2), not pixels.
   */
  function camTop() {
    var spanY = viewTilesY();
    if (spanY >= H) return 0;
    var t = currentTarget();
    var dir = t ? Math.sign(t.anchor.cellY - walker.row) : 0;
    var top = walker.row + dir * Math.floor(spanY / 3) - Math.floor(spanY / 2);
    if (top < 0) top = 0;
    if (top > H - spanY) top = H - spanY;
    return top;
  }
  /**
   * Horizontal window: centred on the walker and clamped to the world, PLUS one adjustment —
   * if the walker's current target is off the left or right edge, the window slides the
   * minimum distance that brings it in.
   *
   * WHY, MEASURED RATHER THAN ASSUMED. The nearest anchor to the spawn is
   * 四条烏丸交差点 東側横断歩道 at column 20. The window is 20 columns wide and camLeft clamps
   * to 0, so at spawn the window is columns 0..19 and the target sits exactly ONE column
   * outside it. The CLAMP, not the distance, is what hides it: the target does not enter the
   * view until x=11, so the first TEN steps show an empty world while S1 counts 20 m down to
   * 10 m. That attacks P1's goal directly — "the first key press gets a response from the
   * world" — because for those ten steps only the HUD responds; the world does not.
   *
   * Sliding the window one column makes the world answer on the first step. The walker stays
   * strictly inside the window either way (P13 asserts it at every step) and the horizontal
   * field of view is unchanged, so this is not a camera redesign — it is the same 20-column
   * window choosing where to sit. §1.5's vertical bias is untouched and still applies.
   */
  function camLeft() {
    var span = viewTilesX();
    var left = walker.x - Math.floor(span / 2);
    /* HARD RULE FIRST: the walker never leaves the frame (asserted at every step by P13).
       So the window is clamped to the world BEFORE any attempt to reach the target — at the
       western end the walker is AT the boundary, the window is 0..19, and there is simply no
       room to slide toward a target at column 20.
       My first version of this nudged toward the target first, which pushed the window to
       1..20 at spawn and put the walker OUTSIDE it. P13 caught that on the very first frame
       with 1,371 violations across the walk — the assertion was written for exactly this and
       it worked. A rule that keeps the target visible must never outrank one that keeps the
       PLAYER visible. */
    if (left < 0) left = 0;
    if (left > W - span) left = W - span;
    var t = currentTarget();
    if (t) {
      if (t.anchor.cellX > left + span - 1) left = Math.min(t.anchor.cellX - span + 1, walker.x);
      else if (t.anchor.cellX < left) left = Math.max(t.anchor.cellX, walker.x - span + 1);
      if (left < 0) left = 0;
      if (left > W - span) left = W - span;
    }
    return left;
  }
  /** Integer-cell deadzone at the current zoom (spec §1.5: 192x96 px -> 3x2 cells at zoom 2). */
  function deadzoneX() { return Math.max(1, Math.round(192 / TILE_PX / screenScale())); }
  function deadzoneY() { return Math.max(1, Math.round(96 / TILE_PX / screenScale())); }

  var cv = document.getElementById('c');
  var ctx = cv.getContext('2d');
  var img = null;

  function paint() {
    var S = scale();
    var span = viewTilesX();
    var left = camLeft();
    var top = camTop();
    var spanY = viewTilesY();
    var pw = span * S, ph = spanY * S;
    if (cv.width !== pw || cv.height !== ph) {
      cv.width = pw; cv.height = ph;
      img = ctx.createImageData(pw, ph);
    }
    var d = img.data;
    var si = Math.round(S);            // integer blit size so tiles never half-pixel
    /**
     * THE WORLD LAYER IS BLANK (spec §1.3): blank ground + the street centreline + the
     * walker + the anchors. The collision, ground and height rasters are NOT drawn.
     *
     * They were drawn in every previous version, and that was the reason the first frame
     * read as an abstract diagram: a visitor sees dark blobs and grey blocks and has no way
     * to know they are buildings. Those rasters are still the collision truth — the walker
     * is still refused by them, asserted every step — they are simply not the visual.
     */
    for (var ty = 0; ty < spanY; ty++) {
      var r = top + ty;
      for (var tx = 0; tx < span; tx++) {
        var x = left + tx;
        var i = (r >= 0 && r < H && x >= 0 && x < W) ? r * W + x : -1;
        var R = 246, G = 242, B = 234;
        if (i < 0) { R = 255; G = 255; B = 255; }
        var art = cellPixelSource(x, r);
        var y0 = ty * si, x0 = tx * si;
        for (var oy = 0; oy < si; oy++) {
          var pyy = y0 + oy;
          if (pyy >= ph) break;
          var rowBase = (pyy * pw + x0) * 4;
          for (var ox = 0; ox < si; ox++) {
            var pxx = x0 + ox;
            if (pxx >= pw) break;
            var o = rowBase + ox * 4;
            if (art) {
              // sample the 32x32 source; nearest-neighbour, which is what pixel art wants
              var sx = Math.min(art.width - 1, Math.floor((ox * art.width) / si));
              var sy = Math.min(art.height - 1, Math.floor((oy * art.height) / si));
              var so = (sy * art.width + sx) * 4;
              d[o] = art.data[so]; d[o + 1] = art.data[so + 1]; d[o + 2] = art.data[so + 2];
              d[o + 3] = art.data[so + 3];
            } else {
              d[o] = R; d[o + 1] = G; d[o + 2] = B; d[o + 3] = 255;
            }
          }
        }
      }
    }
    var si2 = Math.round(S);
    /**
     * ANCHORS. Ten doorways and up to six places, drawn as programmatic marks — no assets,
     * which is what lets P1 run with a $0 spend (SOW §6.3).
     *
     * A door with NO modelled interior is drawn differently from one that opens into a
     * room, so the world does not present a placeholder as if it were a room. It is still
     * drawn and still enterable — only the POINTING is gated by eligible.
     */
    for (var k = 0; k < PAYLOAD.anchors.length; k++) {
      var an = PAYLOAD.anchors[k];
      var ax0 = Math.round((an.cellX - left) * S), ay0 = Math.round((an.cellY - top) * S);
      if (ax0 < -si2 || ay0 < -si2 || ax0 > pw || ay0 > ph) continue;
      var isDoor = an.kind === 'doorway';
      var mark = isDoor ? (an.modelled ? [176, 24, 24] : [214, 138, 26])   // red = room, amber = placeholder
                        : [30, 90, 160];                                   // blue = a real place
      for (var yy = 0; yy < si2; yy++) for (var xx = 0; xx < si2; xx++) {
        var px2 = ax0 + xx, py2 = ay0 + yy;
        if (px2 < 0 || py2 < 0 || px2 >= pw || py2 >= ph) continue;
        var oo = (py2 * pw + px2) * 4;
        // places are drawn hollow so they cannot be mistaken for doors
        var edge = !isDoor && (xx === 0 || yy === 0 || xx === si2 - 1 || yy === si2 - 1);
        if (!isDoor && !edge) continue;
        d[oo] = mark[0]; d[oo + 1] = mark[1]; d[oo + 2] = mark[2]; d[oo + 3] = 255;
      }
    }
    ctx.putImageData(img, 0, 0);
    // the street's own centreline, the thing the walker follows
    ctx.strokeStyle = '#1F6B3A'; ctx.lineWidth = 1.5; ctx.beginPath();
    var started = false;
    for (var x2 = left; x2 <= left + span; x2++) {
      if (x2 < 0 || x2 >= W) continue;
      var row = SIM.streetRowAt(PAYLOAD.street.profile, PAYLOAD.halfCrossTiles, x2);
      if (row === null) continue;
      var cx = (x2 - left) * S + S / 2, cy = (row - top) * S + S / 2;
      if (!started) { ctx.moveTo(cx, cy); started = true; } else ctx.lineTo(cx, cy);
    }
    ctx.stroke();
    /**
     * TRAIL as squares; the WALKER as a narrow directional mark. Spec §1.3 requires the
     * walker to be a DIFFERENT SHAPE from its own trail — previously both were squares in
     * the same green, so after three steps "which one am I" was legible only by opacity.
     * Facing = last movement direction, and east at t=0.
     */
    ctx.fillStyle = 'rgba(31,107,58,.22)';
    for (var i2 = 0; i2 < trail.length; i2++) {
      var tr = trail[i2];
      if (tr.x < left || tr.x > left + span) continue;
      ctx.fillRect((tr.x - left) * S, (tr.row - top) * S, S, S);
    }
    var wx = (walker.x - left) * S, wy = (walker.row - top) * S;
    var cxw = wx + S / 2, cyw = wy + S / 2;
    ctx.fillStyle = '#16161D';
    ctx.beginPath();
    if (facing === 'E')      { ctx.moveTo(wx + S - 1, cyw); ctx.lineTo(wx + 2, wy + 2); ctx.lineTo(wx + 2, wy + S - 2); }
    else if (facing === 'W') { ctx.moveTo(wx + 1, cyw);     ctx.lineTo(wx + S - 2, wy + 2); ctx.lineTo(wx + S - 2, wy + S - 2); }
    else if (facing === 'N') { ctx.moveTo(cxw, wy + 1);     ctx.lineTo(wx + 2, wy + S - 2); ctx.lineTo(wx + S - 2, wy + S - 2); }
    else                     { ctx.moveTo(cxw, wy + S - 1); ctx.lineTo(wx + 2, wy + 2);     ctx.lineTo(wx + S - 2, wy + 2); }
    ctx.closePath();
    ctx.fill();
  }

  /* --- the walker and the two growing sets ---------------------------- *
   * derived and read are the whole progression model, and they are the save (spec
   * §1.7). They hold ids, never sentences and never times. At t=0 both are empty — that
   * is asserted, because an empty-at-spawn progression is what makes P1's first frame
   * comparable between subjects.
   */
  var walker = { x: PAYLOAD.walk.path.length ? PAYLOAD.walk.path[0].x : 0, row: PAYLOAD.walk.path[0].row };
  var trail = [];
  var refusals = 0;
  var derived = {};
  var read = {};
  var facing = 'E';                 // spec §1.3: facing = last movement direction, east at t=0
  var keyLog = [];
  var t0 = null;

  /** All key handling goes through here, so the log cannot miss a press. */
  function logKey(key, refused) {
    if (t0 === null) t0 = Date.now();
    var t = currentTarget();
    keyLog.push({
      t_ms: Date.now() - t0,
      key: key === null ? null : String(key),
      refused: refused === true,
      targetId: t ? t.anchor.id : null,
      targetDistM: t ? t.dist : null,
      derivedCount: Object.keys(derived).length,
    });
  }

  var _lastTarget = null;
  /** The current target, recomputed from scratch each time. No caching, no script. */
  function currentTarget() {
    return SIM.nextAnchor(PAYLOAD.anchors, walker, derived);
  }

  /** Try one step. Refuses if the destination is blocked — that IS the collision test. */
  /**
   * One simulation step. derived grows when the walker STANDS ON the anchor it was
   * pointed at — the whole progression rule, and it contains no sentences and no times
   * (spec §1.7: the save IS these two sets).
   */
  function step(dx, dr) {
    var nx = walker.x + dx, nr = walker.row + dr;
    if (SIM.isBlocked(collision, nx, nr, W, H)) { refusals++; return false; }
    walker.x = nx; walker.row = nr;
    if (dx > 0) facing = 'E'; else if (dx < 0) facing = 'W';
    else if (dr < 0) facing = 'N'; else if (dr > 0) facing = 'S';
    trail.push({ x: nx, row: nr });
    if (trail.length > 2000) trail.shift();
    reachCheck();
    return true;
  }

  /** Standing on the named anchor marks it derived. No key press, no confirmation. */
  function reachCheck() {
    var t = currentTarget();
    if (!t) return;
    if (t.anchor.cellX === walker.x && t.anchor.cellY === walker.row) {
      derived[t.anchor.id] = true;
      read[t.anchor.id] = true;   // having arrived is the strongest form of having read
    }
  }

  var KEYS = {
    ArrowRight: [1, 0], ArrowLeft: [-1, 0], ArrowUp: [0, -1], ArrowDown: [0, 1],
    d: [1, 0], a: [-1, 0], w: [0, -1], s: [0, 1]
  };
  window.addEventListener('keydown', function (e) {
    if (e.key === '[') { zoomIdx = Math.max(0, zoomIdx - 1); update(); e.preventDefault(); return; }
    if (e.key === ']') { zoomIdx = Math.min(ZOOM_LEVELS.length - 1, zoomIdx + 1); update(); e.preventDefault(); return; }
    var lower = e.key && e.key.toLowerCase ? e.key.toLowerCase() : e.key;
    var k = KEYS[e.key] || KEYS[lower];
    if (k) {
      e.preventDefault();
      var before = JSON.stringify(displayState());
      logKey(e.key, null);
      step(k[0], k[1]);
      var after = JSON.stringify(displayState());
      keyLog[keyLog.length - 1].changed = before !== after;
      update();
      return;
    }
    if (lower === 'e') { e.preventDefault(); logKey(e.key, null); openNearestDoor(); update(); return; }
    // an unmapped key IS data: a person trying something the page does not accept.
    logKey(e.key, true);
    keyLog[keyLog.length - 1].changed = false;
  });

  /** The displayed quantities. changed in the log is computed against THIS. */
  function displayState() {
    var t = currentTarget();
    var c = SIM.counters(PAYLOAD.anchors, derived, PAYLOAD.guideCounts);
    return {
      x: walker.x, row: walker.row,
      s1Visible: !SIM.isVisible(t ? t.anchor : null, camLeft(), camTop(), viewTilesX(), viewTilesY()),
      s1Dist: t ? t.dist : null,
      s2: [c.streetDone, c.doorDone],
      s3Nearest: t ? t.anchor.id : null,
    };
  }

  /* --- the interaction -------------------------------------------------
     "Open" means: a door within reach of the walker. The outcome is decided by
     SIM.openDoor against the DECLARATION in PAYLOAD.openerContract — not by the
     collision layer, and not here. */
  function nearestDoor() {
    var best = null, bestD = null;
    for (var i = 0; i < PAYLOAD.doors.length; i++) {
      var d = PAYLOAD.doors[i];
      var dist = Math.abs(d.cellX - walker.x) + Math.abs(d.cellY - walker.row);
      if (bestD === null || dist < bestD) { bestD = dist; best = d; }
    }
    return bestD !== null && bestD <= 3 ? best : null;
  }

  var lastInteraction = null;

  function openNearestDoor() {
    var d = nearestDoor();
    if (!d) { lastInteraction = null; document.getElementById('s4').className = 'slot hidden'; return; }
    var outcome = SIM.openDoor(d.doorId, PAYLOAD.openerContract, PAYLOAD);
    lastInteraction = outcome;
    renderReceipt(outcome);
  }

  /**
   * S4 — the doorway receipt. The title leads with a real discriminator (door id +
   * along-street metre), because seven of the ten doors share one building name and a
   * receipt reading 京都三井ビルディング seven times tells a visitor nothing about where
   * they are. Those seven doors really do stand at seven measured positions, so showing
   * that uses existing data rather than manufacturing content.
   *
   * The 值已核 column is written out as an explicit "none, and why" when empty. A blank column
   * reads as a broken page, and 四条烏丸交差点's name genuinely is a LICENCED label while
   * its coordinates are observed.
   */
  function renderReceipt(o) {
    var anchor = null;
    for (var i = 0; i < PAYLOAD.anchors.length; i++) if (PAYLOAD.anchors[i].id === o.doorId) anchor = PAYLOAD.anchors[i];
    var title = SIM.anchorTitle(anchor);
    var html = '<div class="lbl">门口回执</div><div class="val t">' + esc(title.title) + '</div>' +
      '<div class="n">' + esc(title.sub || '') + '</div>';
    if (o.placeholder) {
      html += '<div class="ph-flag">' + esc(o.placeholder) + '</div>' +
        '<div class="n">' + esc(o.placeholderNote) + '</div>' +
        '<div class="n">门位是 <code>authored</code>：没有任何人观察过它。</div>';
    } else if (o.annotation) {
      html += '<div class="ok-flag">measured interior</div><div class="n">' + esc(o.annotation) + '</div>' +
        '<div class="n">' + esc(o.annotationZh || '') + '</div>' +
        '<div class="n">门位是 <code>authored</code>：没有任何人观察过它。</div>';
    }
    // two columns, never merged: 你到过 / 值已核
    var visited = derived[o.doorId] ? '你到过' : '未到过';
    var verifiedCount = anchor && anchor.verifiedFields ? anchor.verifiedFields.length : 0;
    html += '<div class="n">' + visited + ' · 值已核：' +
      (verifiedCount > 0 ? verifiedCount + ' 项' : '无（此名称来自授权模板）') + '</div>';
    if (anchor && anchor.sourceUrl) html += '<div class="n">' + esc(anchor.sourceUrl) + '</div>';
    var el = document.getElementById('s4');
    el.className = 'slot';
    el.innerHTML = html;
  }

  /**
   * The panel. This is where the north/south distinction has to be legible to
   * someone who knows nothing about the project.
   *
   * A MODELLED surface prints an annotation that states only what was measured.
   * An UNMODELLED surface prints the placeholder and NOTHING ELSE about the inside,
   * and no diagram is drawn for it: an absent diagram is honest, an invented one is
   * the defect the card forbids.
   */
  function renderPanel(message, o) {
    var el = document.getElementById('panel');
    if (message) { el.className = 'panel'; el.innerHTML = '<b>' + message + '</b>'; return; }
    if (!o) { el.className = 'panel'; el.innerHTML = ''; return; }
    var html = '';
    html += '<div class="ph-title">' + esc(o.doorId) + ' · ' + esc(o.title) + '</div>';
    if (o.placeholder) {
      // THE placeholder. One string, and the note says plainly that no layout is shown.
      html += '<div class="ph-flag">' + esc(o.placeholder) + '</div>';
      html += '<div class="ph-note">' + esc(o.placeholderNote) + '</div>';
      html += '<div class="ph-note">' + esc(o.kind) + ' — the shopfront exists in the world; this version has no interior for it, so nothing is drawn.</div>';
    } else if (o.annotation) {
      html += '<div class="ok-flag">measured interior</div>';
      html += '<div class="ph-note">' + esc(o.annotation) + '</div>';
      html += '<div class="ph-note">' + esc(o.annotationZh || '') + '</div>';
      if (o.drawRoom) {
        // The ONLY thing drawn for a real room: its measured extent, 1 px per row, with
        // a hatch marking the back wall. No furniture, no plan, no invented layout.
        html += '<canvas id="room" width="' + (o.measuredInteriorRows * 24 + 2) + '" height="26"></canvas>';
        html += '<div class="ph-note">the hatched strip is ' + o.measuredInteriorRows + ' row(s) deep — this is the room\\'s MEASURED EXTENT, not a floor plan</div>';
      }
    } else {
      html += '<div class="ph-flag">' + esc(o.kind) + '</div>';
    }
    el.className = 'panel';
    el.innerHTML = html;
    if (o.drawRoom && o.measuredInteriorRows) drawRoomStrip(o.measuredInteriorRows);
  }

  function drawRoomStrip(rows) {
    var rc = document.getElementById('room');
    if (!rc || !rc.getContext) return;
    var g = rc.getContext('2d');
    if (!g) return;
    g.fillStyle = '#e8f0e8'; g.fillRect(0, 0, rc.width, rc.height);
    g.fillStyle = '#1F6B3A'; g.fillRect(0, 0, 2, rc.height);            // doorway
    g.fillStyle = '#cfe0cf'; g.fillRect(2, 4, rows * 24, rc.height - 8); // the measured extent
    g.fillStyle = '#16161D';                                            // the back wall, hatched
    for (var x = 2 + rows * 24; x < 2 + rows * 24 + 6 && x < rc.width; x += 2) g.fillRect(x, 0, 1, rc.height);
  }

  function esc(s) {
    return String(s === null || s === undefined ? '' : s)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  }

  /**
   * THE FOUR HUD SLOTS (spec §1.4). Exactly four, each a pure function of the state:
   *   S1 edge indicator  — direction + integer metres; HIDDEN once next is on screen
   *   S2 three counters  — 街上 n/6 · 门洞 n/10 · 街外 16, three denominators from input
   *   S3 status readout  — 四条通 · 东行 x m · 最近 <real name> ±d m
   *   S4 doorway receipt — only while a door is open
   *
   * The 10-row debug table and the "E open a door" line are GONE (card deliverable 2).
   * That line mattered: it was the only thing telling anyone E existed, and P1 is the
   * experiment that asks whether it is needed. It is present in V-B only, as a keymap that
   * names keys and nothing else.
   */
  function update() {
    paint();
    var t = currentTarget();
    var tAnchor = t ? t.anchor : null;
    var inWin = SIM.isVisible(tAnchor, camLeft(), camTop(), viewTilesX(), viewTilesY());
    var c = SIM.counters(PAYLOAD.anchors, derived, PAYLOAD.guideCounts);

    /* S1 — hidden when the target is on screen (it would be repeating the world) */
    var s1 = document.getElementById('s1');
    if (tAnchor === null) {
      s1.className = 'slot hidden';
    } else if (inWin) {
      s1.className = 'slot hidden';
    } else {
      s1.className = 'slot';
      var dx = tAnchor.cellX - walker.x, dy = tAnchor.cellY - walker.row;
      var arrow = Math.abs(dx) >= Math.abs(dy) ? (dx >= 0 ? '→' : '←') : (dy >= 0 ? '↑' : '↓');
      s1.innerHTML = '<div class="lbl">目标 ' + esc(arrow) + '</div>' +
        '<div class="val"><span class="arrow">' + arrow + '</span> <span class="m">' + t.dist + ' m</span> ' +
        '<span class="n">' + esc(tAnchor.nameJa) + '</span></div>';
    }

    /* S2 — three counters, never merged; the third is total minus in-window */
    document.getElementById('s2').innerHTML =
      '<div class="lbl">计数</div><div class="val count">街上 <b>' + c.streetDone + '</b>/' + c.streetTotal +
      ' · 门洞 <b>' + c.doorDone + '</b>/' + c.doorTotal + ' · 街外 <b>' + c.outsideTotal + '</b></div>';

    /* S3 — the name is a VALUE from the fact layer, never a string written here.
       It reports the NEAREST anchor, which is a different question from next: nearest is
       ungated and will name a placeholder door, while next skips placeholders. */
    var near = SIM.nearestAnchor(PAYLOAD.anchors, walker);
    var st = SIM.statusReadout(near ? near.anchor : null, walker);
    document.getElementById('s3').innerHTML =
      '<div class="lbl">位置</div><div class="val">' + esc(st.street) + ' · ' + esc(st.direction) +
      ' <b>' + st.alongM + '</b> m' +
      (st.nearestName ? ' · 最近 <b>' + esc(st.nearestName) + '</b> ±' + st.nearestDistM + ' m' : '') + '</div>';
  }

  /* --- the key log: "which second was the first press" is a FILE, not a memory --- */
  document.getElementById('logbtn').addEventListener('click', function () {
    document.getElementById('logtext').value = JSON.stringify(keyLog, null, 1);
  });
  update();

  /**
   * THE VARIANT. V-A is bare; V-B adds a keymap that names KEYS AND NOTHING ELSE — no
   * goal, no colour legend. That is the whole point of the pair: it separates "the keys
   * were not discoverable" from "there was no reason to press one". A keymap that also
   * explained the goal would confound exactly the thing it exists to isolate.
   *
   * Chosen by URL fragment so both variants are one file and open from file://:
   *   index.html        -> V-A (bare, the default)
   *   index.html#V-B    -> V-B (keymap)
   */
  var VARIANT = (function () {
    var h = (location.hash || '').replace(/^#/, '').toUpperCase();
    return PAYLOAD.variants[h] ? h : PAYLOAD.defaultVariant;
  })();
  (function applyVariant() {
    var v = PAYLOAD.variants[VARIANT];
    document.getElementById('variantLabel').textContent = VARIANT + (v.keymap ? ' (keymap)' : ' (bare)');
    var km = document.getElementById('keymap');
    if (v.keymap && v.instructionalText.length) {
      km.className = '';
      km.textContent = v.instructionalText.join('  ·  ');
    } else {
      km.className = 'hidden';
      km.textContent = '';
    }
  })();

  // expose for a headless probe, and for a curious person with a console
  window.__TG = { walker: walker, step: step, update: update, refusals: function () { return refusals; },
                  SIM: SIM, collision: collision, isBlocked: SIM.isBlocked, W: W, H: H,
                  zoom: function () { return zoomLevel(); }, camLeft: camLeft, camTop: camTop,
                  tilePx: TILE_PX, screenPxPerTile: scale, viewTilesX: viewTilesX, viewTilesY: viewTilesY,
                  hasTileAssets: function () { return TILE_ASSETS !== null; },
                  openNearestDoor: openNearestDoor, nearestDoor: nearestDoor,
                  lastInteraction: function () { return lastInteraction; },
                  openerContract: PAYLOAD.openerContract,
                  /* P1 state, for the assertions and for the log export */
                  variant: VARIANT, variantSpec: PAYLOAD.variants[VARIANT],
                  anchors: PAYLOAD.anchors, derived: derived, read: read,
                  currentTarget: currentTarget, displayState: displayState,
                  keyLog: function () { return keyLog; },
                  facing: function () { return facing; },
                  keymapVisible: function () { return document.getElementById('keymap').className === ''; },
                  keymapText: function () { return document.getElementById('keymap').textContent; } };
  update();
})();
</script>
</body>
</html>
`;

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(OUT, html, 'utf8');

const sha = sha256Hex(Buffer.from(html, 'utf8'));
/**
 * Report the two numbers as the two different things they are. "7/10 enterable" was
 * the old phrasing and the ruling made it false: every door is enterable now, and what
 * differs is whether an interior is MODELLED behind it.
 */
const placeholderOnly = doorMarkers.filter((d) => d.interaction && d.interaction.placeholder).length;
const modelled = doorMarkers.filter((d) => d.interaction && d.interaction.drawRoom).length;
const reachableCount = doorMarkers.filter((d) => d.reachable).length;

const out = [];
out.push('bake-viewer — the walkable shell');
out.push(`  scene      : ${SCENE_SHA}  (${buf.length} B, ${W}x${H})`);
out.push(`  contract   : ${payload.scene.contractHash}`);
out.push(`  guide      : ${payload.guide.placeCount} place ids reconciled (${payload.guide.stopCount} stops + ${payload.guide.nearbyCount} alongside)`);
out.push(`  street     : drift ${payload.street.driftSpanM} m · rows ${payload.walk.startRow} -> ${payload.walk.endRow}`);
out.push(`  walk       : reached x=${payload.walk.reachedX} of ${W - 1} in ${payload.walk.steps} steps, ${payload.walk.corrections} correction(s)`);
out.push(`  doors      : ${doorMarkers.length} total, all openable · ${reachableCount} reachable from the street · ` +
  `${modelled} open into a modelled interior · ${placeholderOnly} placeholder only`);
out.push(`  simulation : ${simSource.length} B serialised out of check-viewer.mjs (same bodies, not a copy)`);
out.push(`  page       : ${OUT}`);
out.push(`               ${html.length} B, single file, no network`);
out.push(`               sha256 ${sha}`);
out.push('');
out.push(`  open it    : Start-Process "${OUT}"      (Windows)`);
out.push(`               open "${OUT}"               (macOS)`);
out.push(`               xdg-open "${OUT}"           (Linux)`);
out.push('  no server is needed: every layer is inlined, so file:// works.');
process.stdout.write(`${out.join('\n')}\n`);
process.exitCode = 0;
