name: End-to-End Tests

on:
  schedule:
    - cron: '0 0 * * 1,4'  # Run every Monday and Thursday at midnight
  pull_request:
    branches: 
      - main
      - develop
      - 'release-*'
  workflow_dispatch:       # Allow manual triggering

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Install Playwright
        run: npx playwright install --with-deps
      
      - name: Build Application
        run: npm run build
      
      - name: Start Application
        run: |
          npm run start:server &
          npm run start:client &
          npx wait-on http://localhost:3000 http://localhost:5000/api/health
      
      - name: Run Playwright Tests
        run: npx playwright test --config=tests/config/playwright.config.js
      
      - name: Store Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: docs/project_lifecycle/all_tests/results/playwright-test/
          retention-days: 14
      
      - name: Store Playwright Screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-screenshots
          path: docs/project_lifecycle/all_tests/results/playwright-test/screenshots/
          retention-days: 14
          
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            playwright-report/*.xml 